/**
 * HiveForge — unified domain model & Provider contract.
 *
 * Phase 1 of docs/architecture/HIVEFORGE-CONSOLIDATION.md: type definitions only.
 * Nothing in this file is wired into HiveForgeService, the gateway routes, or any
 * UI yet — it does not change runtime behavior. It exists so phase 2 (wrapping the
 * existing simulator as `SimulatorProvider implements HiveForgeProvider`) and phase 3
 * (Prisma-backed repository) have a stable contract to build against.
 *
 * Sourced from, and intended to replace:
 *  - This domain's own `ProvisionedResource` (hiveforge.ts) — kept as-is until phase 3.
 *  - app/platform/hiveforge/core/contracts/state.ts (ResourceState/ResourceHealth — salvaged verbatim)
 *  - app/platform/hiveforge/core/contracts/provider.ts (ProviderContract's descriptive fields +
 *    IProvisioningProvider's actuation methods, merged and typed against real domain types)
 *  - prisma/hiveforge_schema_additions.prisma's `Resource` model (persisted shape)
 */

import type { CatalogCategoryId } from "./catalog.js";
import type { ResourceKind, SizeTier } from "./hiveforge.js";

// ---------------------------------------------------------------------------
// Canonical lifecycle vocabulary (salvaged from core/contracts/state.ts)
// ---------------------------------------------------------------------------

/**
 * Canonical resource lifecycle states. Supersedes both the simulator's narrow
 * `"provisioning" | "running" | "stopped" | "deprovisioned"` union (hiveforge.ts,
 * of which only "running"/"deprovisioned" are ever actually assigned today) and
 * Prisma's untyped `status: String` column. Not yet applied to either — phase 3
 * migrates `ProvisionedResource`/`Resource` onto this vocabulary.
 */
export type ResourceState =
  | "Draft"
  | "Provisioning"
  | "Deploying"
  | "Running"
  | "Scaling"
  | "Updating"
  | "Suspended"
  | "Failed"
  | "Recovering"
  | "Deleting"
  | "Archived";

export type ResourceHealth = "Healthy" | "Warning" | "Critical" | "Unknown";

export interface ResourceStateTransition {
  from: ResourceState;
  to: ResourceState;
  timestamp: string;
  reason?: string;
  actorId?: string;
}

// ---------------------------------------------------------------------------
// Unified resource domain type
// ---------------------------------------------------------------------------

/**
 * The single resource shape the consolidated HiveForge is meant to converge on,
 * replacing four incompatible candidates found during the audit: this domain's
 * `ProvisionedResource`, Prisma's `Resource`, and core/contracts' `URD` and
 * `InventoryResource` (the latter two have no producers today and are dropped
 * outright rather than migrated).
 *
 * Field provenance:
 *  - id, kind, category, subgroup, itemId, itemName, region, sizeTier, replicas,
 *    options, specs, endpoint, hourlyRateUsd, createdAt: from ProvisionedResource
 *    (the only shape any provisioning code actually populates today).
 *  - workspaceId, providerId, blueprintId, cost, config: from Prisma's Resource
 *    row, for the phase-3 persistence layer.
 *  - state, health, transitions: from the canonical vocabulary above.
 */
export interface HiveForgeResource {
  id: string;
  organizationId: string;
  workspaceId?: string;

  kind: ResourceKind;
  category: CatalogCategoryId;
  subgroup: string;
  itemId: string;
  itemName: string;

  providerId: string;
  blueprintId?: string;

  region: string;
  sizeTier: SizeTier;
  replicas?: number;
  options: string[];
  specs: Record<string, unknown>;
  endpoint: string;

  state: ResourceState;
  health: ResourceHealth;
  transitions: ResourceStateTransition[];

  hourlyRateUsd: number;
  /** Accrued cost at last computation — mirrors Prisma's `cost` column; recomputed by costExplorer-equivalent logic, not stored authoritatively until a caching need is demonstrated. */
  cost: number;

  config?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deprovisionedAt?: string;
}

// ---------------------------------------------------------------------------
// Provider contract — synthesized, not inherited from either existing shape
// ---------------------------------------------------------------------------

export interface ProviderIdentity {
  id: string;
  vendor: string;
  version: string;
}

export interface ProviderRegion {
  id: string;
  name: string;
  availabilityZones: string[];
  latencyTier: "low" | "medium" | "high";
}

export interface ProviderCapabilities {
  /** Catalog categories (see catalog.ts) this provider can actually fulfill. Empty/absent = all (simulator behavior). */
  supportedCategories?: CatalogCategoryId[];
}

export interface CostEstimate {
  currency: "USD";
  hourlyAmount: number;
  monthlyAmount: number;
}

export interface ProvisionSpec {
  /** Pre-generated by the caller (not the provider) so a provider can treat provision() as idempotent on retry. */
  id: string;
  itemId: string;
  kind: ResourceKind;
  region?: string;
  sizeTier: SizeTier;
  replicas?: number;
  options: string[];
  /** Catalog base rate before size-tier scaling; the provider applies its own scaling/multipliers. */
  baseHourlyRateUsd?: number;
}

export interface ProvisionResult {
  /** Region actually used — echoes spec.region if set, otherwise the provider's own choice (e.g. random pick among its regions, as SimulatorProvider does today). */
  region: string;
  specs: Record<string, unknown>;
  endpoint: string;
  hourlyRateUsd: number;
  /** Initial state immediately after provision() returns — SimulatorProvider returns "Running" synchronously; a real cloud provider would return "Provisioning" and require a caller to poll getStatus(). */
  initialState: ResourceState;
}

/**
 * The seam neither existing implementation actually has today. Synthesized from
 * ProviderContract's descriptive fields (identity/capabilities/regions/estimateCost)
 * and IProvisioningProvider's actuation methods (create/delete → provision/deprovision),
 * but typed against real domain types instead of `any`/`unknown`.
 *
 * `SimulatorProvider` (phase 2) wraps HiveForgeService's existing specsFor()/provision()/
 * deprovision() logic behind this interface, unchanged in behavior, and becomes the
 * default, always-registered implementation — not a special case alongside "real" providers.
 */
export interface HiveForgeProvider {
  identity: ProviderIdentity;
  capabilities: ProviderCapabilities;
  regions: ProviderRegion[];

  estimateCost(spec: ProvisionSpec): Promise<CostEstimate>;
  provision(spec: ProvisionSpec): Promise<ProvisionResult>;
  deprovision(resourceId: string): Promise<void>;
  getStatus(resourceId: string): Promise<{ state: ResourceState; health: ResourceHealth }>;
}
