apiVersion: v1
kind: Namespace
metadata:
  name: cerebro-hive
  labels:
    app.kubernetes.io/part-of: cerebro-hive
    app.kubernetes.io/managed-by: argocd
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerebro-hive
  namespace: cerebro-hive
  labels:
    app.kubernetes.io/part-of: cerebro-hive
automountServiceAccountToken: false
