apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: cerebro-hive
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 8900
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
