/**
 * HiveSwarm — Task DAG Types (HS-101 / HS-102)
 *
 * Represents a directed acyclic graph of tasks with typed dependency edges.
 * The DAG is the primary unit of work submitted to the Swarm Runtime.
 */

import type { CapabilityRequirement } from "./capability.js";
import type { TaskBudget, TaskInput, TaskPriority } from "./task.js";

// ── Dependency types ──────────────────────────────────────────────────────────

/**
 * Each edge in the task graph has a dependency type that governs
 * how the scheduler dispatches downstream tasks.
 */
export type DependencyType =
  | "sequential"       // Target starts only after source completes (success only)
  | "parallel"         // Both tasks can run concurrently (no data dependency)
  | "conditional"      // Target runs if a condition on the source output is true
  | "dynamic"          // Target task is generated at runtime from source output
  | "loop"             // Source is retried in a loop until exit criterion is met
  | "human_approval";  // Target requires explicit human sign-off before proceeding

// ── DAG Node ─────────────────────────────────────────────────────────────────

export interface TaskNode {
  /** Unique within the DAG, referenced by edges */
  id:           string;
  name:         string;
  description:  string;

  capability:   CapabilityRequirement;
  input:        Omit<TaskInput, "dependsOn">;  // dependsOn derived from edges
  budget?:      TaskBudget;
  priority?:    TaskPriority;

  /** For loop nodes: the exit condition (evaluated against each iteration output) */
  loopExitCondition?: string;
  /** Max loop iterations (default 10) */
  maxLoopIterations?: number;

  /** For human_approval edges: who can approve (role or user IDs) */
  approvers?: string[];

  metadata: Record<string, unknown>;
}

// ── DAG Edge ─────────────────────────────────────────────────────────────────

export interface TaskEdge {
  /** Source node ID */
  source: string;
  /** Target node ID */
  target: string;
  /** Governs how scheduler treats this connection */
  type:   DependencyType;

  /**
   * For conditional edges: a JSONPath or JS expression evaluated against
   * the source node's output. If falsy, the target node is skipped.
   * Example: "$.result.confidence > 0.8"
   */
  condition?: string;

  /**
   * For dynamic edges: a template expression for the target task's input.
   * Source output is available as `$output` in the template.
   */
  dynamicInputTemplate?: string;
}

// ── Validation error ──────────────────────────────────────────────────────────

export interface DAGValidationError {
  code:    "CYCLE_DETECTED" | "MISSING_NODE" | "ORPHAN_NODE" | "INVALID_EDGE" | "MISSING_ENTRY";
  message: string;
  nodeIds?: string[];
}

// ── Task DAG ─────────────────────────────────────────────────────────────────

export interface TaskDAG {
  /** Unique DAG definition ID (content-addressed in production) */
  id:          string;
  name:        string;
  description: string;
  version:     number;

  nodes: TaskNode[];
  edges: TaskEdge[];

  /** IDs of nodes with no incoming edges (run first) */
  entryNodes:  string[];
  /** IDs of nodes with no outgoing edges (must all complete for DAG to succeed) */
  exitNodes:   string[];

  /** Overall budget for the entire DAG run */
  totalBudget?: TaskBudget;
  /** Default priority applied to nodes that don't specify one */
  defaultPriority: TaskPriority;

  createdAt: string;
  metadata:  Record<string, unknown>;
}

// ── DAG Run ───────────────────────────────────────────────────────────────────

export type RunStatus =
  | "pending" | "running" | "paused" | "awaiting_approval"
  | "completed" | "failed" | "cancelled";

export interface DAGRun {
  /** ULID generated by swarm-runtime on submission */
  id:       string;
  dagId:    string;
  tenantId: string;
  userId:   string;

  status:   RunStatus;

  /** task.id → taskStatus: provides a live view of the run */
  taskStatuses: Record<string, import("./task.js").TaskStatus>;

  /** Temporal workflow execution ID for durable tracking */
  temporalRunId?: string;

  input:     Record<string, unknown>;
  output?:   Record<string, unknown>;

  startedAt?:   string;
  completedAt?: string;
  createdAt:    string;

  metadata: Record<string, unknown>;
}
