apiVersion: v1
kind: Service
metadata:
  name: forge-api
  namespace: cerebro-hive
  labels:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: forge-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: forge-api
  ports:
    - name: http
      port: 4005
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
