// ============================================================
// Agent OS — Seed Data
// ============================================================
import type {
  AgentOsDatabase,
  AgentDefinition,
  AgentInstance,
  Mission,
  Task,
  ExecutionRun,
  ApprovalRequest,
  AuditEvent,
  Policy,
  BudgetAccount,
  Tool,
} from "./types";

// ── Deterministic IDs so relationships are consistent ────────

const IDS = {
  // Agents
  planner: "agent_planner_001",
  research: "agent_research_002",
  codeAnalysis: "agent_codeanalysis_003",
  finance: "agent_finance_004",
  customerSuccess: "agent_custsuccess_005",
  dataEngineer: "agent_dataengr_006",
  securityAudit: "agent_secaudit_007",
  reportGen: "agent_reportgen_008",

  // Tools
  toolSearch: "tool_search_001",
  toolGithub: "tool_github_002",
  toolJira: "tool_jira_003",
  toolSlack: "tool_slack_004",
  toolDatabase: "tool_database_005",
  toolEmail: "tool_email_006",
  toolCalendar: "tool_calendar_007",
  toolAnalytics: "tool_analytics_008",

  // Missions
  mission1: "msn_comp_intel_001",
  mission2: "msn_q3_revenue_002",

  // Tasks — Mission 1 (Competitive Intel)
  ci_task1: "tsk_ci_gather_001",
  ci_task2: "tsk_ci_analysis_002",
  ci_task3: "tsk_ci_code_audit_003",
  ci_task4: "tsk_ci_report_004",
  ci_task5: "tsk_ci_distribute_005",

  // Tasks — Mission 2 (Q3 Revenue)
  q3_task1: "tsk_q3_segment_001",
  q3_task2: "tsk_q3_pricing_002",
  q3_task3: "tsk_q3_campaigns_003",

  // Execution Runs
  run1: "run_ci_gather_001",
  run2: "run_ci_analysis_001",
  run3: "run_ci_report_001",
  run4: "run_q3_segment_001",
  run5: "run_q3_pricing_001",

  // Instances
  inst1: "inst_planner_ci_001",
  inst2: "inst_research_ci_001",
  inst3: "inst_report_ci_001",
  inst4: "inst_finance_q3_001",
  inst5: "inst_data_q3_001",

  // Approvals
  apr1: "apr_finance_001",
  apr2: "apr_prod_write_002",
  apr3: "apr_data_access_003",

  // Policies
  pol1: "pol_high_cost_001",
  pol2: "pol_prod_write_002",
  pol3: "pol_data_pii_003",
  pol4: "pol_rate_limit_004",
  pol5: "pol_critical_agent_005",

  // Budgets
  bud_tenant: "bud_tenant_001",
  bud_m1: "bud_mission1_001",
  bud_m2: "bud_mission2_001",
};

function d(offsetDays: number, offsetHours = 0): string {
  const dt = new Date("2026-08-01T09:00:00Z");
  dt.setDate(dt.getDate() + offsetDays);
  dt.setHours(dt.getHours() + offsetHours);
  return dt.toISOString();
}

// ── Tools ────────────────────────────────────────────────────

const tools: Tool[] = [
  {
    toolId: IDS.toolSearch,
    name: "WebSearch",
    provider: "Nexarch/Internal",
    description: "Performs internet searches and returns ranked results with snippets.",
    capabilities: ["search", "retrieve", "summarize"],
    schema: {
      input: { query: "string", maxResults: "number" },
      output: { results: "array<{title,url,snippet}>" },
    },
    riskLevel: "low",
    rateLimitPerMin: 30,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolGithub,
    name: "GitHubTool",
    provider: "GitHub",
    description: "Read and write GitHub repositories, issues, PRs, and code files.",
    capabilities: ["read_repo", "write_repo", "create_pr", "search_code"],
    schema: {
      input: { repo: "string", action: "string", payload: "object" },
      output: { result: "object", url: "string" },
    },
    riskLevel: "medium",
    rateLimitPerMin: 15,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolJira,
    name: "JiraTool",
    provider: "Atlassian",
    description: "Create, read, update and close Jira issues and epics.",
    capabilities: ["create_issue", "update_issue", "search_issues", "close_issue"],
    schema: {
      input: { project: "string", action: "string", fields: "object" },
      output: { issueKey: "string", url: "string" },
    },
    riskLevel: "low",
    rateLimitPerMin: 20,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolSlack,
    name: "SlackTool",
    provider: "Slack",
    description: "Post messages, read channel history, and manage Slack notifications.",
    capabilities: ["post_message", "read_channel", "dm_user", "create_channel"],
    schema: {
      input: { channel: "string", action: "string", text: "string" },
      output: { ts: "string", ok: "boolean" },
    },
    riskLevel: "low",
    rateLimitPerMin: 60,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolDatabase,
    name: "DatabaseTool",
    provider: "Nexarch/Internal",
    description: "Execute read and write queries against the production data warehouse.",
    capabilities: ["read_query", "write_query", "schema_inspect"],
    schema: {
      input: { sql: "string", params: "array", readOnly: "boolean" },
      output: { rows: "array", rowCount: "number" },
    },
    riskLevel: "high",
    rateLimitPerMin: 10,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolEmail,
    name: "EmailTool",
    provider: "SendGrid",
    description: "Send transactional and bulk emails via SendGrid.",
    capabilities: ["send_email", "send_bulk", "get_status"],
    schema: {
      input: { to: "string|array", subject: "string", body: "string", template: "string?" },
      output: { messageId: "string", status: "string" },
    },
    riskLevel: "medium",
    rateLimitPerMin: 10,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolCalendar,
    name: "CalendarTool",
    provider: "Google",
    description: "Read and write Google Calendar events, schedules, and meeting invites.",
    capabilities: ["list_events", "create_event", "update_event", "delete_event"],
    schema: {
      input: { calendarId: "string", action: "string", event: "object?" },
      output: { eventId: "string", htmlLink: "string" },
    },
    riskLevel: "low",
    rateLimitPerMin: 20,
    enabled: true,
    createdAt: d(-30),
  },
  {
    toolId: IDS.toolAnalytics,
    name: "AnalyticsTool",
    provider: "Mixpanel",
    description: "Query Mixpanel for user behaviour, funnel metrics, and retention data.",
    capabilities: ["funnel_query", "retention_query", "event_query", "cohort_query"],
    schema: {
      input: { report: "string", dateRange: "object", filters: "object?" },
      output: { data: "array", meta: "object" },
    },
    riskLevel: "low",
    rateLimitPerMin: 15,
    enabled: true,
    createdAt: d(-30),
  },
];

// ── Policies ─────────────────────────────────────────────────

const policies: Policy[] = [
  {
    policyId: IDS.pol1,
    name: "Require Approval for High-Cost Operations",
    description: "Any agent action with an estimated cost > $5 USD must receive human approval before execution.",
    enabled: true,
    priority: 1,
    condition: { field: "estimatedCostUsd", operator: "gt", value: 5 },
    action: "require_approval",
    createdAt: d(-30),
  },
  {
    policyId: IDS.pol2,
    name: "Block Production Write Without Approval",
    description: "Deny all write operations targeting production databases unless an active approval exists.",
    enabled: true,
    priority: 2,
    condition: { field: "toolId", operator: "eq", value: IDS.toolDatabase },
    action: "require_approval",
    createdAt: d(-30),
  },
  {
    policyId: IDS.pol3,
    name: "PII Data Access Gate",
    description: "Agents with riskLevel 'high' or 'critical' must route any PII query through a security review.",
    enabled: true,
    priority: 3,
    condition: { field: "agentRiskLevel", operator: "in", value: ["high", "critical"] },
    action: "require_approval",
    createdAt: d(-30),
  },
  {
    policyId: IDS.pol4,
    name: "Rate-Limit External Search",
    description: "Throttle WebSearch calls to 30 per minute per agent instance.",
    enabled: true,
    priority: 4,
    condition: { field: "toolId", operator: "eq", value: IDS.toolSearch },
    action: "rate_limit",
    createdAt: d(-30),
  },
  {
    policyId: IDS.pol5,
    name: "Quarantine on Critical Risk Escalation",
    description: "Automatically quarantine any agent that self-escalates to critical risk level during runtime.",
    enabled: true,
    priority: 5,
    condition: { field: "runtimeRiskLevel", operator: "eq", value: "critical" },
    action: "deny",
    createdAt: d(-30),
  },
];

// ── Agent Definitions ────────────────────────────────────────

const agents: AgentDefinition[] = [
  {
    id: IDS.planner,
    name: "PlannerAgent",
    version: "2.1.0",
    type: "planner",
    role: "Mission Orchestrator",
    description: "Decomposes high-level missions into structured task graphs, assigns agents, and monitors progress.",
    purpose: "Translate strategic objectives into executable agent task plans with dependency resolution.",
    owner: "platform-team@nexarch.io",
    riskLevel: "medium",
    trustLevel: 90,
    capabilities: ["task_decomposition", "agent_assignment", "dependency_resolution", "progress_tracking"],
    toolPermissions: [IDS.toolJira, IDS.toolSlack],
    modelPolicy: {
      allowedModels: ["claude-opus-4-5", "claude-sonnet-4-5"],
      preferredModel: "claude-opus-4-5",
      maxContextTokens: 200000,
      temperature: 0.3,
    },
    defaultBudget: { tokenBudget: 500000, costBudgetUsd: 25, period: "mission" },
    tags: ["orchestration", "planning", "core"],
    createdAt: d(-60),
    updatedAt: d(-5),
    isDeprecated: false,
  },
  {
    id: IDS.research,
    name: "ResearchAgent",
    version: "1.4.2",
    type: "executor",
    role: "Market & Technical Researcher",
    description: "Conducts deep research using web search, news aggregation, and internal knowledge bases.",
    purpose: "Gather high-fidelity intelligence on competitors, market trends, and technical landscapes.",
    owner: "strategy-team@nexarch.io",
    riskLevel: "low",
    trustLevel: 85,
    capabilities: ["web_search", "document_analysis", "summarization", "citation_tracking"],
    toolPermissions: [IDS.toolSearch, IDS.toolSlack, IDS.toolEmail],
    modelPolicy: {
      allowedModels: ["claude-sonnet-4-5", "claude-haiku-4-5"],
      preferredModel: "claude-sonnet-4-5",
      maxContextTokens: 150000,
      temperature: 0.4,
    },
    defaultBudget: { tokenBudget: 300000, costBudgetUsd: 15, period: "mission" },
    tags: ["research", "intelligence", "market"],
    createdAt: d(-55),
    updatedAt: d(-2),
    isDeprecated: false,
  },
  {
    id: IDS.codeAnalysis,
    name: "CodeAnalysisAgent",
    version: "1.2.0",
    type: "specialist",
    role: "Code & Architecture Analyst",
    description: "Analyses codebases for quality, security vulnerabilities, and architectural patterns.",
    purpose: "Evaluate competitor and internal code quality; surface technical risk and innovation signals.",
    owner: "engineering@nexarch.io",
    riskLevel: "low",
    trustLevel: 88,
    capabilities: ["code_review", "security_scan", "dependency_analysis", "architecture_diagram"],
    toolPermissions: [IDS.toolGithub, IDS.toolSearch],
    modelPolicy: {
      allowedModels: ["claude-sonnet-4-5"],
      preferredModel: "claude-sonnet-4-5",
      maxContextTokens: 100000,
      temperature: 0.2,
    },
    defaultBudget: { tokenBudget: 200000, costBudgetUsd: 10, period: "mission" },
    tags: ["code", "security", "analysis"],
    createdAt: d(-50),
    updatedAt: d(-10),
    isDeprecated: false,
  },
  {
    id: IDS.finance,
    name: "FinanceAgent",
    version: "3.0.1",
    type: "specialist",
    role: "Financial Analyst & Modeller",
    description: "Builds financial models, pricing analyses, and revenue impact projections with high accuracy.",
    purpose: "Provide data-driven financial forecasts and pricing strategy recommendations for revenue optimisation.",
    owner: "finance@nexarch.io",
    riskLevel: "high",
    trustLevel: 92,
    capabilities: ["financial_modelling", "pricing_analysis", "revenue_forecasting", "sensitivity_analysis"],
    toolPermissions: [IDS.toolDatabase, IDS.toolAnalytics, IDS.toolEmail],
    modelPolicy: {
      allowedModels: ["claude-opus-4-5", "claude-sonnet-4-5"],
      preferredModel: "claude-opus-4-5",
      maxContextTokens: 180000,
      temperature: 0.1,
    },
    defaultBudget: { tokenBudget: 400000, costBudgetUsd: 20, period: "mission" },
    tags: ["finance", "revenue", "pricing"],
    createdAt: d(-45),
    updatedAt: d(-1),
    isDeprecated: false,
  },
  {
    id: IDS.customerSuccess,
    name: "CustomerSuccessAgent",
    version: "1.1.5",
    type: "specialist",
    role: "Customer Segment & Retention Analyst",
    description: "Identifies at-risk customers, growth opportunities, and personalised success playbooks.",
    purpose: "Drive NRR improvement by surfacing retention risks and upsell opportunities at the account level.",
    owner: "cs-team@nexarch.io",
    riskLevel: "medium",
    trustLevel: 80,
    capabilities: ["churn_prediction", "upsell_identification", "health_scoring", "playbook_generation"],
    toolPermissions: [IDS.toolDatabase, IDS.toolAnalytics, IDS.toolSlack, IDS.toolEmail],
    modelPolicy: {
      allowedModels: ["claude-sonnet-4-5", "claude-haiku-4-5"],
      preferredModel: "claude-sonnet-4-5",
      maxContextTokens: 120000,
      temperature: 0.5,
    },
    defaultBudget: { tokenBudget: 250000, costBudgetUsd: 12, period: "mission" },
    tags: ["customer-success", "retention", "nrr"],
    createdAt: d(-40),
    updatedAt: d(-3),
    isDeprecated: false,
  },
  {
    id: IDS.dataEngineer,
    name: "DataEngineerAgent",
    version: "2.0.0",
    type: "executor",
    role: "Data Pipeline & ETL Specialist",
    description: "Designs, executes, and validates data pipelines; manages schema migrations and data quality.",
    purpose: "Ensure reliable, high-quality data flows that underpin analytics and AI decision-making.",
    owner: "data-platform@nexarch.io",
    riskLevel: "high",
    trustLevel: 87,
    capabilities: ["pipeline_design", "etl_execution", "schema_migration", "data_quality_check"],
    toolPermissions: [IDS.toolDatabase, IDS.toolGithub, IDS.toolJira],
    modelPolicy: {
      allowedModels: ["claude-sonnet-4-5"],
      preferredModel: "claude-sonnet-4-5",
      maxContextTokens: 120000,
      temperature: 0.2,
    },
    defaultBudget: { tokenBudget: 350000, costBudgetUsd: 18, period: "mission" },
    tags: ["data-engineering", "etl", "pipelines"],
    createdAt: d(-35),
    updatedAt: d(-7),
    isDeprecated: false,
  },
  {
    id: IDS.securityAudit,
    name: "SecurityAuditAgent",
    version: "1.3.0",
    type: "reviewer",
    role: "Security & Compliance Auditor",
    description: "Scans systems for vulnerabilities, audits access controls, and validates compliance posture.",
    purpose: "Maintain continuous security assurance and flag compliance gaps before they become incidents.",
    owner: "security@nexarch.io",
    riskLevel: "high",
    trustLevel: 95,
    capabilities: ["vulnerability_scan", "access_audit", "compliance_check", "threat_modelling"],
    toolPermissions: [IDS.toolGithub, IDS.toolDatabase, IDS.toolSearch, IDS.toolSlack],
    modelPolicy: {
      allowedModels: ["claude-opus-4-5"],
      preferredModel: "claude-opus-4-5",
      maxContextTokens: 200000,
      temperature: 0.1,
    },
    defaultBudget: { tokenBudget: 450000, costBudgetUsd: 22, period: "mission" },
    tags: ["security", "compliance", "audit"],
    createdAt: d(-30),
    updatedAt: d(-4),
    isDeprecated: false,
  },
  {
    id: IDS.reportGen,
    name: "ReportGeneratorAgent",
    version: "1.0.3",
    type: "executor",
    role: "Insight & Report Author",
    description: "Synthesises research, analysis, and data outputs into structured executive reports and presentations.",
    purpose: "Transform raw agent outputs into polished, decision-ready artifacts for human stakeholders.",
    owner: "platform-team@nexarch.io",
    riskLevel: "low",
    trustLevel: 82,
    capabilities: ["report_drafting", "data_visualisation", "executive_summary", "slide_generation"],
    toolPermissions: [IDS.toolEmail, IDS.toolSlack, IDS.toolCalendar],
    modelPolicy: {
      allowedModels: ["claude-sonnet-4-5", "claude-haiku-4-5"],
      preferredModel: "claude-sonnet-4-5",
      maxContextTokens: 150000,
      temperature: 0.6,
    },
    defaultBudget: { tokenBudget: 200000, costBudgetUsd: 10, period: "mission" },
    tags: ["reporting", "synthesis", "communication"],
    createdAt: d(-25),
    updatedAt: d(-2),
    isDeprecated: false,
  },
];

// ── Instances ────────────────────────────────────────────────

const instances: AgentInstance[] = [
  {
    instanceId: IDS.inst1,
    agentId: IDS.planner,
    agentName: "PlannerAgent",
    state: "completed",
    missionId: IDS.mission1,
    delegationChain: [],
    tokensUsed: 42850,
    costUsd: 2.14,
    executionTimeMs: 18400,
    toolCallsMade: 6,
    iterations: 3,
    tokenBudget: 500000,
    costBudgetUsd: 25,
    priority: 9,
    startedAt: d(0),
    lastHeartbeatAt: d(0, 5),
    retryCount: 0,
    traceId: "trace_ci_plan_001",
    errorHistory: [],
  },
  {
    instanceId: IDS.inst2,
    agentId: IDS.research,
    agentName: "ResearchAgent",
    state: "completed",
    missionId: IDS.mission1,
    taskId: IDS.ci_task1,
    parentInstanceId: IDS.inst1,
    delegationChain: [IDS.inst1],
    tokensUsed: 95200,
    costUsd: 4.76,
    executionTimeMs: 64200,
    toolCallsMade: 22,
    iterations: 8,
    tokenBudget: 300000,
    costBudgetUsd: 15,
    priority: 7,
    startedAt: d(0, 1),
    lastHeartbeatAt: d(0, 3),
    retryCount: 0,
    traceId: "trace_ci_research_001",
    errorHistory: [],
  },
  {
    instanceId: IDS.inst3,
    agentId: IDS.reportGen,
    agentName: "ReportGeneratorAgent",
    state: "completed",
    missionId: IDS.mission1,
    taskId: IDS.ci_task4,
    parentInstanceId: IDS.inst1,
    delegationChain: [IDS.inst1],
    tokensUsed: 38100,
    costUsd: 1.91,
    executionTimeMs: 29000,
    toolCallsMade: 4,
    iterations: 2,
    tokenBudget: 200000,
    costBudgetUsd: 10,
    priority: 6,
    startedAt: d(4, 2),
    lastHeartbeatAt: d(4, 4),
    retryCount: 0,
    traceId: "trace_ci_report_001",
    errorHistory: [],
  },
  {
    instanceId: IDS.inst4,
    agentId: IDS.finance,
    agentName: "FinanceAgent",
    state: "running",
    missionId: IDS.mission2,
    taskId: IDS.q3_task2,
    delegationChain: [],
    tokensUsed: 61400,
    costUsd: 3.07,
    executionTimeMs: 41000,
    toolCallsMade: 11,
    iterations: 5,
    tokenBudget: 400000,
    costBudgetUsd: 20,
    priority: 8,
    startedAt: d(7),
    lastHeartbeatAt: d(7, 6),
    retryCount: 0,
    traceId: "trace_q3_finance_001",
    errorHistory: [],
  },
  {
    instanceId: IDS.inst5,
    agentId: IDS.dataEngineer,
    agentName: "DataEngineerAgent",
    state: "waiting",
    missionId: IDS.mission2,
    taskId: IDS.q3_task3,
    delegationChain: [],
    tokensUsed: 12300,
    costUsd: 0.62,
    executionTimeMs: 8500,
    toolCallsMade: 3,
    iterations: 1,
    tokenBudget: 350000,
    costBudgetUsd: 18,
    priority: 7,
    startedAt: d(7, 2),
    lastHeartbeatAt: d(7, 5),
    retryCount: 0,
    traceId: "trace_q3_data_001",
    errorHistory: [],
  },
];

// ── Missions ─────────────────────────────────────────────────

const missions: Mission[] = [
  {
    missionId: IDS.mission1,
    title: "Competitive Intelligence Analysis",
    description:
      "Comprehensive analysis of top 5 competitors across product capabilities, pricing, customer reviews, and technical architecture to inform our H2 product roadmap.",
    objective:
      "Produce an executive-ready competitive landscape report with actionable differentiation recommendations.",
    status: "completed",
    tenantId: "tenant_nexarch_main",
    createdBy: "sarah.chen@nexarch.io",
    assignedAgentIds: [IDS.planner, IDS.research, IDS.codeAnalysis, IDS.reportGen],
    taskIds: [IDS.ci_task1, IDS.ci_task2, IDS.ci_task3, IDS.ci_task4, IDS.ci_task5],
    constraints: {
      deadline: d(7),
      maxCostUsd: 150,
      riskTolerance: "medium",
    },
    events: [
      {
        eventId: "evt_ci_001",
        timestamp: d(0),
        type: "mission_started",
        description: "Mission initiated by sarah.chen@nexarch.io. PlannerAgent assigned as orchestrator.",
        agentId: IDS.planner,
      },
      {
        eventId: "evt_ci_002",
        timestamp: d(0, 1),
        type: "task_started",
        description: "ResearchAgent began gathering competitive intelligence from web sources.",
        agentId: IDS.research,
        taskId: IDS.ci_task1,
      },
      {
        eventId: "evt_ci_003",
        timestamp: d(1),
        type: "task_completed",
        description: "Research phase completed. 47 sources indexed, 5 competitor profiles built.",
        agentId: IDS.research,
        taskId: IDS.ci_task1,
      },
      {
        eventId: "evt_ci_004",
        timestamp: d(2),
        type: "task_started",
        description: "CodeAnalysisAgent started reviewing public GitHub repos of top 3 competitors.",
        agentId: IDS.codeAnalysis,
        taskId: IDS.ci_task3,
      },
      {
        eventId: "evt_ci_005",
        timestamp: d(4),
        type: "task_completed",
        description: "Analysis complete. Report draft ready for review by stakeholders.",
        agentId: IDS.reportGen,
        taskId: IDS.ci_task4,
      },
      {
        eventId: "evt_ci_006",
        timestamp: d(5),
        type: "mission_completed",
        description: "Mission completed successfully. Report distributed to 12 stakeholders.",
        agentId: IDS.planner,
      },
    ],
    artifacts: [
      {
        artifactId: "art_ci_report_001",
        name: "Competitive Intelligence Report Q3 2026",
        type: "pdf",
        url: "/artifacts/ci-report-q3-2026.pdf",
        createdAt: d(4, 3),
      },
      {
        artifactId: "art_ci_data_001",
        name: "Competitor Feature Matrix",
        type: "spreadsheet",
        url: "/artifacts/feature-matrix-q3.xlsx",
        createdAt: d(3),
      },
    ],
    createdAt: d(-1),
    updatedAt: d(5),
    completedAt: d(5),
  },
  {
    missionId: IDS.mission2,
    title: "Q3 Revenue Optimization",
    description:
      "Identify and execute revenue optimisation levers across customer segmentation, pricing model adjustments, and targeted re-engagement campaigns to hit $2.4M ARR target.",
    objective:
      "Deliver a prioritised revenue playbook and execute the top 3 quick-wins by end of Q3.",
    status: "running",
    tenantId: "tenant_nexarch_main",
    createdBy: "marcus.okafor@nexarch.io",
    assignedAgentIds: [IDS.planner, IDS.customerSuccess, IDS.finance, IDS.dataEngineer],
    taskIds: [IDS.q3_task1, IDS.q3_task2, IDS.q3_task3],
    constraints: {
      deadline: d(30),
      maxCostUsd: 300,
      riskTolerance: "high",
    },
    events: [
      {
        eventId: "evt_q3_001",
        timestamp: d(6),
        type: "mission_started",
        description: "Mission kicked off by marcus.okafor@nexarch.io. PlannerAgent building task graph.",
        agentId: IDS.planner,
      },
      {
        eventId: "evt_q3_002",
        timestamp: d(6, 2),
        type: "task_started",
        description: "CustomerSuccessAgent analysing 2,400 accounts for segmentation and health scoring.",
        agentId: IDS.customerSuccess,
        taskId: IDS.q3_task1,
      },
      {
        eventId: "evt_q3_003",
        timestamp: d(7),
        type: "task_completed",
        description: "Segmentation complete. 3 high-value cohorts identified: 140 at-risk, 78 upsell-ready, 32 churn-imminent.",
        agentId: IDS.customerSuccess,
        taskId: IDS.q3_task1,
      },
      {
        eventId: "evt_q3_004",
        timestamp: d(7),
        type: "approval_requested",
        description: "FinanceAgent requested approval to run pricing model update against production DB.",
        agentId: IDS.finance,
        taskId: IDS.q3_task2,
        metadata: { approvalId: IDS.apr2 },
      },
    ],
    artifacts: [],
    createdAt: d(6),
    updatedAt: d(7, 6),
  },
];

// ── Tasks ────────────────────────────────────────────────────

const tasks: Task[] = [
  // Mission 1 — Competitive Intelligence
  {
    taskId: IDS.ci_task1,
    missionId: IDS.mission1,
    name: "Gather Competitive Intelligence",
    description: "Scrape and synthesise data from competitor websites, G2, Capterra, LinkedIn, and tech blogs.",
    objective: "Build structured profiles for each of the 5 target competitors.",
    assignedAgentId: IDS.research,
    status: "completed",
    priority: 9,
    dependencies: [],
    input: { competitors: ["Acme Corp", "DataFlow Inc", "NeuralBase", "OmegaAI", "Synaptic Labs"] },
    output: { profiles: 5, sourcesIndexed: 47, confidenceScore: 0.87 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(0, 1),
    completedAt: d(1),
    createdAt: d(0),
    updatedAt: d(1),
    executionRunIds: [IDS.run1],
  },
  {
    taskId: IDS.ci_task2,
    missionId: IDS.mission1,
    name: "Competitive Feature Analysis",
    description: "Cross-compare feature sets, pricing tiers, and release velocity using gathered data.",
    objective: "Produce a scored feature comparison matrix.",
    assignedAgentId: IDS.research,
    status: "completed",
    priority: 8,
    dependencies: [IDS.ci_task1],
    input: { profileIds: [IDS.ci_task1] },
    output: { featureMatrix: "48x5", topGaps: 7, differentiators: 4 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(1, 2),
    completedAt: d(2),
    createdAt: d(0),
    updatedAt: d(2),
    executionRunIds: [IDS.run2],
  },
  {
    taskId: IDS.ci_task3,
    missionId: IDS.mission1,
    name: "Code Architecture Audit",
    description: "Analyse public GitHub repos and technical blog posts to infer competitor tech stack and architecture choices.",
    objective: "Identify technical moats, risks, and innovation signals.",
    assignedAgentId: IDS.codeAnalysis,
    status: "completed",
    priority: 7,
    dependencies: [IDS.ci_task1],
    output: { reposAnalysed: 12, techStackInsights: 9, securityFlags: 2 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(2),
    completedAt: d(3, 3),
    createdAt: d(0),
    updatedAt: d(3, 3),
    executionRunIds: [],
  },
  {
    taskId: IDS.ci_task4,
    missionId: IDS.mission1,
    name: "Draft Executive Report",
    description: "Synthesise all research and analysis into a structured executive report with visualisations.",
    objective: "Produce a polished 20-page PDF report ready for the leadership review.",
    assignedAgentId: IDS.reportGen,
    status: "completed",
    priority: 6,
    dependencies: [IDS.ci_task2, IDS.ci_task3],
    output: { pages: 22, charts: 8, recommendations: 12 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(4),
    completedAt: d(4, 5),
    createdAt: d(0),
    updatedAt: d(4, 5),
    executionRunIds: [IDS.run3],
  },
  {
    taskId: IDS.ci_task5,
    missionId: IDS.mission1,
    name: "Distribute Report to Stakeholders",
    description: "Email final report to all stakeholders and post summary in #strategy Slack channel.",
    objective: "Ensure every stakeholder receives the report and summary within 1 hour of sign-off.",
    assignedAgentId: IDS.reportGen,
    status: "completed",
    priority: 5,
    dependencies: [IDS.ci_task4],
    output: { emailsSent: 12, slackPosted: true },
    retryCount: 0,
    maxRetries: 2,
    startedAt: d(5),
    completedAt: d(5, 1),
    createdAt: d(0),
    updatedAt: d(5, 1),
    executionRunIds: [],
  },

  // Mission 2 — Q3 Revenue
  {
    taskId: IDS.q3_task1,
    missionId: IDS.mission2,
    name: "Customer Segmentation Analysis",
    description: "Score all 2,400 active accounts on health, expansion potential, and churn risk.",
    objective: "Output three prioritised cohorts: at-risk, upsell-ready, churn-imminent.",
    assignedAgentId: IDS.customerSuccess,
    status: "completed",
    priority: 9,
    dependencies: [],
    input: { accountCount: 2400, dateRange: "last_90_days" },
    output: { atRisk: 140, upsellReady: 78, churnImminent: 32 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(6, 2),
    completedAt: d(7),
    createdAt: d(6),
    updatedAt: d(7),
    executionRunIds: [IDS.run4],
  },
  {
    taskId: IDS.q3_task2,
    missionId: IDS.mission2,
    name: "Pricing Model Optimisation",
    description: "Run sensitivity analysis on current pricing tiers and model impact of proposed changes on MRR.",
    objective: "Recommend top 2 pricing adjustments with projected ARR impact.",
    assignedAgentId: IDS.finance,
    status: "awaiting_approval",
    priority: 8,
    dependencies: [IDS.q3_task1],
    input: { currentMRR: 198000, targetARR: 2400000 },
    retryCount: 0,
    maxRetries: 3,
    startedAt: d(7),
    createdAt: d(6),
    updatedAt: d(7, 4),
    executionRunIds: [IDS.run5],
  },
  {
    taskId: IDS.q3_task3,
    missionId: IDS.mission2,
    name: "Re-engagement Campaign Execution",
    description: "Build and execute personalised email campaigns for each of the three customer cohorts.",
    objective: "Send 250 personalised emails within 48 hours of pricing model approval.",
    assignedAgentId: IDS.dataEngineer,
    status: "waiting_dependency",
    priority: 7,
    dependencies: [IDS.q3_task2],
    retryCount: 0,
    maxRetries: 3,
    createdAt: d(6),
    updatedAt: d(7, 2),
    executionRunIds: [],
  },
];

// ── Execution Runs ────────────────────────────────────────────

const executions: ExecutionRun[] = [
  {
    runId: IDS.run1,
    taskId: IDS.ci_task1,
    missionId: IDS.mission1,
    agentId: IDS.research,
    instanceId: IDS.inst2,
    status: "completed",
    attempt: 1,
    input: { competitors: ["Acme Corp", "DataFlow Inc", "NeuralBase", "OmegaAI", "Synaptic Labs"] },
    output: { profiles: 5, sourcesIndexed: 47 },
    tokensUsed: 95200,
    costUsd: 4.76,
    durationMs: 64200,
    modelCalls: [
      {
        callId: "mc_r1_001",
        model: "claude-sonnet-4-5",
        promptTokens: 14200,
        completionTokens: 8100,
        costUsd: 1.12,
        latencyMs: 4200,
        timestamp: d(0, 1),
      },
      {
        callId: "mc_r1_002",
        model: "claude-sonnet-4-5",
        promptTokens: 38400,
        completionTokens: 14500,
        costUsd: 2.64,
        latencyMs: 6800,
        timestamp: d(0, 2),
      },
    ],
    toolCalls: [
      {
        callId: "tc_r1_001",
        toolId: IDS.toolSearch,
        toolName: "WebSearch",
        input: { query: "Acme Corp product pricing 2026", maxResults: 10 },
        output: { results: [{ title: "Acme Pricing", url: "https://acme.io/pricing", snippet: "..." }] },
        latencyMs: 1200,
        timestamp: d(0, 1),
      },
    ],
    policyDecisions: [
      {
        policyId: IDS.pol4,
        policyName: "Rate-Limit External Search",
        action: "rate_limit",
        reason: "Search call within rate limit — allowed with throttle applied.",
        timestamp: d(0, 1),
      },
    ],
    startedAt: d(0, 1),
    completedAt: d(1),
    createdAt: d(0, 1),
  },
  {
    runId: IDS.run2,
    taskId: IDS.ci_task2,
    missionId: IDS.mission1,
    agentId: IDS.research,
    instanceId: IDS.inst2,
    status: "completed",
    attempt: 1,
    input: { profileIds: [IDS.ci_task1] },
    output: { featureMatrix: "48x5" },
    tokensUsed: 52400,
    costUsd: 2.62,
    durationMs: 38000,
    modelCalls: [
      {
        callId: "mc_r2_001",
        model: "claude-sonnet-4-5",
        promptTokens: 28600,
        completionTokens: 10800,
        costUsd: 1.97,
        latencyMs: 5100,
        timestamp: d(1, 2),
      },
    ],
    toolCalls: [],
    policyDecisions: [],
    startedAt: d(1, 2),
    completedAt: d(2),
    createdAt: d(1, 2),
  },
  {
    runId: IDS.run3,
    taskId: IDS.ci_task4,
    missionId: IDS.mission1,
    agentId: IDS.reportGen,
    instanceId: IDS.inst3,
    status: "completed",
    attempt: 1,
    output: { pages: 22, charts: 8 },
    tokensUsed: 38100,
    costUsd: 1.91,
    durationMs: 29000,
    modelCalls: [
      {
        callId: "mc_r3_001",
        model: "claude-sonnet-4-5",
        promptTokens: 19500,
        completionTokens: 9600,
        costUsd: 1.46,
        latencyMs: 4600,
        timestamp: d(4),
      },
    ],
    toolCalls: [
      {
        callId: "tc_r3_001",
        toolId: IDS.toolSlack,
        toolName: "SlackTool",
        input: { channel: "#strategy", action: "post_message", text: "CI report draft is ready for review." },
        output: { ts: "1722883200.000100", ok: true },
        latencyMs: 380,
        timestamp: d(4, 4),
      },
    ],
    policyDecisions: [],
    startedAt: d(4),
    completedAt: d(4, 5),
    createdAt: d(4),
  },
  {
    runId: IDS.run4,
    taskId: IDS.q3_task1,
    missionId: IDS.mission2,
    agentId: IDS.customerSuccess,
    status: "completed",
    attempt: 1,
    input: { accountCount: 2400 },
    output: { atRisk: 140, upsellReady: 78 },
    tokensUsed: 44700,
    costUsd: 2.24,
    durationMs: 31500,
    modelCalls: [
      {
        callId: "mc_r4_001",
        model: "claude-sonnet-4-5",
        promptTokens: 24100,
        completionTokens: 9600,
        costUsd: 1.68,
        latencyMs: 4900,
        timestamp: d(6, 2),
      },
    ],
    toolCalls: [
      {
        callId: "tc_r4_001",
        toolId: IDS.toolAnalytics,
        toolName: "AnalyticsTool",
        input: { report: "retention_cohort", dateRange: { start: d(-90), end: d(6) } },
        output: { data: [], meta: { rows: 2400 } },
        latencyMs: 1800,
        timestamp: d(6, 2),
      },
    ],
    policyDecisions: [],
    startedAt: d(6, 2),
    completedAt: d(7),
    createdAt: d(6, 2),
  },
  {
    runId: IDS.run5,
    taskId: IDS.q3_task2,
    missionId: IDS.mission2,
    agentId: IDS.finance,
    instanceId: IDS.inst4,
    status: "running",
    attempt: 1,
    input: { currentMRR: 198000, targetARR: 2400000 },
    tokensUsed: 61400,
    costUsd: 3.07,
    durationMs: 0,
    modelCalls: [
      {
        callId: "mc_r5_001",
        model: "claude-opus-4-5",
        promptTokens: 31200,
        completionTokens: 12800,
        costUsd: 2.44,
        latencyMs: 7200,
        timestamp: d(7),
      },
    ],
    toolCalls: [],
    policyDecisions: [
      {
        policyId: IDS.pol2,
        policyName: "Block Production Write Without Approval",
        action: "require_approval",
        reason: "Agent attempted write to production pricing table — approval required.",
        timestamp: d(7, 2),
      },
    ],
    startedAt: d(7),
    createdAt: d(7),
  },
];

// ── Approvals ────────────────────────────────────────────────

const approvals: ApprovalRequest[] = [
  {
    requestId: IDS.apr1,
    agentId: IDS.finance,
    instanceId: IDS.inst4,
    missionId: IDS.mission2,
    taskId: IDS.q3_task2,
    action: "execute_pricing_model_update",
    description:
      "FinanceAgent requests approval to update pricing tier configurations in the production billing database. Estimated MRR impact: +$18,400/month.",
    riskLevel: "high",
    financialImpact: 18400,
    status: "pending",
    requestedAt: d(7, 2),
    expiresAt: d(9),
  },
  {
    requestId: IDS.apr2,
    agentId: IDS.dataEngineer,
    instanceId: IDS.inst5,
    missionId: IDS.mission2,
    taskId: IDS.q3_task3,
    action: "write_production_campaign_table",
    description:
      "DataEngineerAgent requests permission to write 250 personalised campaign records to the production campaigns table before campaign execution begins.",
    riskLevel: "high",
    status: "pending",
    requestedAt: d(7, 3),
    expiresAt: d(9),
  },
  {
    requestId: IDS.apr3,
    agentId: IDS.securityAudit,
    instanceId: "inst_secaudit_standalone_001",
    missionId: IDS.mission1,
    taskId: IDS.ci_task3,
    action: "access_pii_customer_records",
    description:
      "SecurityAuditAgent requests read access to anonymised PII fields in the customer records table to validate GDPR compliance posture.",
    riskLevel: "medium",
    status: "pending",
    requestedAt: d(2, 1),
    expiresAt: d(4),
  },
];

// ── Audit Events ─────────────────────────────────────────────

const audit: AuditEvent[] = [
  {
    eventId: "aud_001",
    timestamp: d(0),
    agentId: IDS.planner,
    instanceId: IDS.inst1,
    missionId: IDS.mission1,
    who: "sarah.chen@nexarch.io",
    what: "Mission 'Competitive Intelligence Analysis' created and PlannerAgent assigned.",
    operation: "mission_create",
    resourceType: "mission",
    resourceId: IDS.mission1,
    outcome: "success",
  },
  {
    eventId: "aud_002",
    timestamp: d(0, 1),
    agentId: IDS.research,
    instanceId: IDS.inst2,
    missionId: IDS.mission1,
    taskId: IDS.ci_task1,
    who: "ResearchAgent",
    what: "ResearchAgent instance spawned for task 'Gather Competitive Intelligence'.",
    operation: "instance_spawn",
    resourceType: "instance",
    resourceId: IDS.inst2,
    outcome: "success",
  },
  {
    eventId: "aud_003",
    timestamp: d(0, 1),
    agentId: IDS.research,
    instanceId: IDS.inst2,
    missionId: IDS.mission1,
    taskId: IDS.ci_task1,
    who: "ResearchAgent",
    what: "WebSearch tool invoked: query 'Acme Corp product pricing 2026'.",
    operation: "tool_call",
    resourceType: "tool",
    resourceId: IDS.toolSearch,
    outcome: "success",
    costUsd: 0.004,
  },
  {
    eventId: "aud_004",
    timestamp: d(1),
    agentId: IDS.research,
    instanceId: IDS.inst2,
    missionId: IDS.mission1,
    taskId: IDS.ci_task1,
    who: "ResearchAgent",
    what: "Task 'Gather Competitive Intelligence' completed successfully. 47 sources indexed.",
    operation: "task_complete",
    resourceType: "task",
    resourceId: IDS.ci_task1,
    outcome: "success",
    costUsd: 4.76,
  },
  {
    eventId: "aud_005",
    timestamp: d(4, 5),
    agentId: IDS.reportGen,
    instanceId: IDS.inst3,
    missionId: IDS.mission1,
    taskId: IDS.ci_task4,
    who: "ReportGeneratorAgent",
    what: "Executive report drafted: 22 pages, 8 charts, 12 recommendations.",
    operation: "task_complete",
    resourceType: "task",
    resourceId: IDS.ci_task4,
    outcome: "success",
    costUsd: 1.91,
  },
  {
    eventId: "aud_006",
    timestamp: d(5),
    agentId: IDS.planner,
    instanceId: IDS.inst1,
    missionId: IDS.mission1,
    who: "PlannerAgent",
    what: "Mission 'Competitive Intelligence Analysis' marked completed.",
    operation: "mission_complete",
    resourceType: "mission",
    resourceId: IDS.mission1,
    outcome: "success",
    costUsd: 15.62,
  },
  {
    eventId: "aud_007",
    timestamp: d(6),
    agentId: IDS.planner,
    instanceId: "inst_planner_q3_001",
    missionId: IDS.mission2,
    who: "marcus.okafor@nexarch.io",
    what: "Mission 'Q3 Revenue Optimization' created.",
    operation: "mission_create",
    resourceType: "mission",
    resourceId: IDS.mission2,
    outcome: "success",
  },
  {
    eventId: "aud_008",
    timestamp: d(7),
    agentId: IDS.customerSuccess,
    instanceId: "inst_cs_q3_001",
    missionId: IDS.mission2,
    taskId: IDS.q3_task1,
    who: "CustomerSuccessAgent",
    what: "Segmentation analysis completed. 250 accounts flagged across 3 cohorts.",
    operation: "task_complete",
    resourceType: "task",
    resourceId: IDS.q3_task1,
    outcome: "success",
    costUsd: 2.24,
  },
  {
    eventId: "aud_009",
    timestamp: d(7, 2),
    agentId: IDS.finance,
    instanceId: IDS.inst4,
    missionId: IDS.mission2,
    taskId: IDS.q3_task2,
    who: "FinanceAgent",
    what: "Policy 'Block Production Write Without Approval' triggered. Approval request created.",
    operation: "policy_deny",
    resourceType: "policy",
    resourceId: IDS.pol2,
    outcome: "failure",
    costUsd: 0,
  },
  {
    eventId: "aud_010",
    timestamp: d(7, 3),
    agentId: IDS.finance,
    instanceId: IDS.inst4,
    missionId: IDS.mission2,
    taskId: IDS.q3_task2,
    who: "FinanceAgent",
    what: "Approval request APR-001 submitted for human review. Task paused pending decision.",
    operation: "approval_request",
    resourceType: "approval",
    resourceId: IDS.apr1,
    outcome: "success",
  },
];

// ── Budgets ──────────────────────────────────────────────────

const budgets: BudgetAccount[] = [
  {
    accountId: IDS.bud_tenant,
    type: "tenant",
    tokenBudget: 50000000,
    costBudgetUsd: 2000,
    tokenUsed: 343950,
    costUsed: 17.22,
    period: "monthly",
    createdAt: d(-30),
    updatedAt: d(7, 6),
  },
  {
    accountId: IDS.bud_m1,
    missionId: IDS.mission1,
    type: "mission",
    tokenBudget: 2000000,
    costBudgetUsd: 150,
    tokenUsed: 228650,
    costUsed: 15.62,
    period: "mission",
    createdAt: d(0),
    updatedAt: d(5),
  },
  {
    accountId: IDS.bud_m2,
    missionId: IDS.mission2,
    type: "mission",
    tokenBudget: 5000000,
    costBudgetUsd: 300,
    tokenUsed: 118400,
    costUsed: 5.93,
    period: "mission",
    createdAt: d(6),
    updatedAt: d(7, 6),
  },
];

// ── Export ────────────────────────────────────────────────────

export function seedDatabase(): AgentOsDatabase {
  return {
    agents,
    instances,
    missions,
    tasks,
    executions,
    approvals,
    audit,
    policies,
    budgets,
    tools,
  };
}
