// =============================================================================
// Mock Provider — deterministic responses for testing / no-API-key environments
// =============================================================================
import type {
  AIService, AIGenerateRequest, AIGenerateResult, AIStreamChunk,
} from '../service/AIService';

const MOCK_PLAN = {
  modules: [
    { name: 'Authentication', priority: 'critical', storyCount: 8, apiCount: 6 },
    { name: 'Patient Management', priority: 'critical', storyCount: 12, apiCount: 8 },
    { name: 'Appointment Booking', priority: 'high', storyCount: 9, apiCount: 6 },
    { name: 'Billing & Invoices', priority: 'high', storyCount: 14, apiCount: 11 },
    { name: 'Pharmacy Module', priority: 'medium', storyCount: 8, apiCount: 7 },
    { name: 'Lab Results', priority: 'medium', storyCount: 7, apiCount: 6 },
  ],
  actors: ['Admin', 'Doctor', 'Nurse', 'Patient', 'Pharmacist', 'Lab Technician', 'Finance Officer'],
  milestones: [
    { title: 'Sprint 1 – Core Setup & Auth', weekLabel: 'Week 1-2', order: 1 },
    { title: 'Sprint 2 – Patient & Doctor Modules', weekLabel: 'Week 3-5', order: 2 },
    { title: 'Sprint 3 – Billing & Pharmacy', weekLabel: 'Week 6-8', order: 3 },
    { title: 'Sprint 4 – Labs & Reporting', weekLabel: 'Week 9-10', order: 4 },
    { title: 'Sprint 5 – Testing & Hardening', weekLabel: 'Week 11-12', order: 5 },
    { title: 'Sprint 6 – Deployment & Launch', weekLabel: 'Week 13-14', order: 6 },
  ],
  totalStories: 58,
  totalApis: 44,
  stack: {
    frontend: 'Next.js 14 + TypeScript + Tailwind CSS',
    backend: 'NestJS + TypeScript',
    database: 'PostgreSQL + Redis + pgvector',
    mobile: 'React Native + Expo',
    infra: 'Docker + Kubernetes + GitHub Actions',
  },
};

async function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms));
}

export class MockProvider implements AIService {
  async generateText(req: AIGenerateRequest): Promise<AIGenerateResult> {
    await sleep(300);
    return {
      text: JSON.stringify(MOCK_PLAN),
      tokensIn: 120,
      tokensOut: 480,
      model: 'mock-v1',
      durationMs: 300,
    };
  }

  async *streamText(req: AIGenerateRequest): AsyncGenerator<AIStreamChunk> {
    const code = `// Generated by CerebroForge™ MockProvider
import { Injectable } from '@nestjs/common';

@Injectable()
export class PatientService {
  async findAll() {
    return [];
  }
}`;
    for (const char of code) {
      await sleep(10);
      yield { delta: char, done: false };
    }
    yield { delta: '', done: true };
  }

  async generateStructured<T>(req: AIGenerateRequest & { schema: string; schemaDescription: string }): Promise<T> {
    await sleep(400);
    return MOCK_PLAN as unknown as T;
  }
}
