
import { StudioGraph } from '../../graph/GraphModel';
import { ExecutionPlan } from '../ir/ExecutionPlan';
import { Diagnostic } from '../CompilerErrors';

export interface CompilerMetrics {
  compilationTimeMs: number;
  passTimings: Record<string, number>;
  nodeCount: number;
  stageCount: number;
  optimizationCount: number;
}

export interface CompilationContext {
  graph: StudioGraph;
  plan: ExecutionPlan;
  diagnostics: Diagnostic[];
  artifacts: Record<string, any>;
  metrics: CompilerMetrics;
}

export interface PassResult {
  context: CompilationContext;
  diagnostics: Diagnostic[]; // Diagnostics specifically generated by this pass
}

export interface CompilerPass {
  id: string;
  phase: string;
  description: string;
  requires?: string[]; // IDs of prerequisite passes
  run: (context: Readonly<CompilationContext>) => PassResult;
}
