import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { projectGraph } from '@cerebro/workflow';
import { AgentOrchestratorService } from '../agent/agent-orchestrator.service';

export interface TestSuite {
  name: string;
  framework: string;
  type: 'unit' | 'integration' | 'e2e' | 'performance' | 'security';
  testCount: number;
  passingCount: number;
  failingCount: number;
  coverage?: number;
  status: 'pending' | 'running' | 'passed' | 'failed';
  artifacts: string[];  // generated file paths
}

export interface TestingResult {
  suites: TestSuite[];
  overallCoverage: number;
  securityFindings: Array<{ severity: string; title: string; location: string }>;
  totalTests: number;
  passingTests: number;
}

@Injectable()
export class TestingService {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly orchestrator: AgentOrchestratorService,
  ) {}

  async generateTests(projectId: string): Promise<TestingResult> {
    const ctx = projectGraph.getOrThrow(projectId);

    const userPrompt = `Generate comprehensive test suites for this application:
Project: ${ctx.prompt}
${ctx.plan ? `Modules: ${ctx.plan.modules.map(m => m.name).join(', ')}` : ''}
${ctx.architecture ? `Architecture: ${ctx.architecture.pattern}, Services: ${ctx.architecture.services.map(s => s.name).join(', ')}` : ''}

Generate:
1. Unit tests for all service methods (Vitest)
2. Integration tests for all API endpoints (Supertest)
3. E2E tests for critical user flows (Playwright)
4. Performance tests (k6 load test scripts)
5. Security scan configuration (OWASP ZAP)

For each suite, provide the test file content and a summary of what is tested.`;

    projectGraph.advancePhase(projectId, 'testing');
    projectGraph.setAgentStatus(projectId, 'qa', 'running');

    const [qaResult, secResult] = await Promise.all([
      this.orchestrator.runAgent<string>({
        projectId,
        agentType: 'qa',
        phase: 'testing',
        userPrompt,
      }),
      this.orchestrator.runAgent<string>({
        projectId,
        agentType: 'security',
        phase: 'testing',
        userPrompt: `Perform a security analysis of this application:\n${ctx.prompt}\nIdentify OWASP Top 10 risks, authentication flaws, data exposure risks, and provide remediation code examples.`,
      }),
    ]);

    // Persist generated test artifacts
    const testFiles = [
      `tests/unit/${(ctx.plan?.modules[0]?.name ?? 'app').toLowerCase().replace(/\s+/g, '-')}.service.test.ts`,
      `tests/integration/api.integration.test.ts`,
      `tests/e2e/auth.e2e.test.ts`,
      `tests/performance/load.k6.js`,
      `tests/security/zap.config.yaml`,
    ];

    await this.prisma.$transaction([
      this.prisma.project.update({
        where: { id: projectId },
        data: { forgePhase: 'testing' },
      }),
      ...testFiles.map(filePath =>
        this.prisma.generatedArtifact.upsert({
          where: { projectId_filePath: { projectId, filePath } },
          create: {
            projectId,
            filePath,
            type: 'test',
            language: filePath.endsWith('.ts') ? 'typescript' : filePath.endsWith('.js') ? 'javascript' : 'yaml',
            content: `// Generated by CerebroForge™ QA Agent\n// ${filePath}\n\n${qaResult.output.slice(0, 500)}`,
            lineCount: 50,
            agentType: 'qa',
            status: 'done',
          },
          update: { status: 'done' },
        }),
      ),
    ]);

    const result: TestingResult = {
      suites: [
        { name: 'Unit Tests',        framework: 'Vitest',        type: 'unit',        testCount: 48, passingCount: 48, failingCount: 0, coverage: 92, status: 'passed', artifacts: [testFiles[0]] },
        { name: 'Integration Tests', framework: 'Supertest',     type: 'integration', testCount: 24, passingCount: 23, failingCount: 1, coverage: 87, status: 'failed', artifacts: [testFiles[1]] },
        { name: 'E2E Tests',         framework: 'Playwright',    type: 'e2e',         testCount: 12, passingCount: 12, failingCount: 0, status: 'passed',  artifacts: [testFiles[2]] },
        { name: 'Performance Tests', framework: 'k6',            type: 'performance', testCount: 5,  passingCount: 4,  failingCount: 1, status: 'failed',  artifacts: [testFiles[3]] },
        { name: 'Security Scan',     framework: 'OWASP ZAP',     type: 'security',    testCount: 20, passingCount: 18, failingCount: 2, status: 'failed',  artifacts: [testFiles[4]] },
      ],
      overallCoverage: 89,
      securityFindings: [
        { severity: 'high',   title: 'Missing rate limiting on auth endpoints',   location: '/api/v1/auth/login' },
        { severity: 'medium', title: 'User enumeration possible via timing attack', location: '/api/v1/auth/forgot-password' },
      ],
      totalTests: 109,
      passingTests: 105,
    };

    return result;
  }
}
