apiVersion: v1
kind: Service
metadata:
  name: studio
  namespace: cerebro-hive
  labels:
    app.kubernetes.io/name: studio
    app.kubernetes.io/component: studio
  annotations:
    # Prometheus service discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: studio
    app.kubernetes.io/component: studio
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
