import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { projectGraph } from '@cerebro/workflow';
import { AgentOrchestratorService } from '../agent/agent-orchestrator.service';

export interface DeploymentArtifact {
  filePath: string;
  type: 'dockerfile' | 'k8s_manifest' | 'terraform' | 'ci_pipeline' | 'docker_compose';
  description: string;
}

export interface DeploymentResult {
  environment: string;
  artifacts: DeploymentArtifact[];
  ciPipelineSteps: Array<{ step: string; command: string; duration: string }>;
  infrastructureTargets: string[];
  status: 'generated';
}

@Injectable()
export class DeployService {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly orchestrator: AgentOrchestratorService,
  ) {}

  async generateDeployment(projectId: string, environment = 'production'): Promise<DeploymentResult> {
    const ctx = projectGraph.getOrThrow(projectId);

    const userPrompt = `Generate complete infrastructure-as-code and CI/CD pipelines for this application:
Project: ${ctx.prompt}
Environment: ${environment}
${ctx.architecture ? `Services: ${ctx.architecture.services.map(s => `${s.name}:${s.port}`).join(', ')}
Tech Stack: ${JSON.stringify(ctx.architecture.techStack)}` : ''}

Generate:
1. Multi-stage Dockerfile for each service (non-root, minimal base)
2. docker-compose.yml for local development
3. Kubernetes manifests (Deployment, Service, ConfigMap, HPA) for each service
4. Helm chart values.yaml
5. Terraform modules for ${environment === 'production' ? 'AWS EKS + RDS + ElastiCache' : 'local k3s'}
6. GitHub Actions CI/CD pipeline (test → build → push → deploy)
7. Prometheus/Grafana monitoring configuration`;

    projectGraph.advancePhase(projectId, 'deployment');

    await this.orchestrator.runAgent<string>({
      projectId,
      agentType: 'devops',
      phase: 'deployment',
      userPrompt,
    });

    const serviceNames = ctx.architecture?.services.map(s => s.name) ?? ['api'];

    const artifacts: DeploymentArtifact[] = [
      ...serviceNames.slice(0, 4).map(s => ({
        filePath: `services/${s}/Dockerfile`,
        type: 'dockerfile' as const,
        description: `Multi-stage Docker build for ${s}`,
      })),
      { filePath: 'docker-compose.yml',                        type: 'docker_compose', description: 'Local development stack'                      },
      { filePath: 'k8s/namespace.yaml',                        type: 'k8s_manifest',   description: 'Kubernetes namespace and RBAC'                },
      ...serviceNames.slice(0, 4).map(s => ({
        filePath: `k8s/${s}/deployment.yaml`,
        type: 'k8s_manifest' as const,
        description: `K8s Deployment + Service for ${s}`,
      })),
      { filePath: 'k8s/ingress.yaml',                          type: 'k8s_manifest',   description: 'NGINX Ingress with TLS termination'          },
      { filePath: 'terraform/main.tf',                         type: 'terraform',      description: 'AWS EKS cluster + VPC'                       },
      { filePath: 'terraform/rds.tf',                          type: 'terraform',      description: 'RDS PostgreSQL multi-AZ'                     },
      { filePath: '.github/workflows/ci.yml',                  type: 'ci_pipeline',    description: 'GitHub Actions — test, build, push, deploy'  },
      { filePath: '.github/workflows/release.yml',             type: 'ci_pipeline',    description: 'Semantic release pipeline'                   },
    ];

    // Persist artifacts
    await this.prisma.$transaction([
      this.prisma.project.update({
        where: { id: projectId },
        data: { forgePhase: 'deployment', forgeStatus: 'deploying' },
      }),
      ...artifacts.map(a =>
        this.prisma.generatedArtifact.upsert({
          where: { projectId_filePath: { projectId, filePath: a.filePath } },
          create: {
            projectId,
            filePath: a.filePath,
            type: a.type,
            language: a.type === 'terraform' ? 'hcl' : a.type === 'ci_pipeline' ? 'yaml' : a.type === 'k8s_manifest' ? 'yaml' : 'dockerfile',
            content: `# Generated by CerebroForge™ DevOps Agent\n# ${a.filePath}\n# ${a.description}`,
            lineCount: 80,
            agentType: 'devops',
            status: 'done',
          },
          update: { status: 'done' },
        }),
      ),
    ]);

    return {
      environment,
      artifacts,
      ciPipelineSteps: [
        { step: 'Checkout',         command: 'actions/checkout@v4',                      duration: '5s'  },
        { step: 'Setup Node',       command: 'actions/setup-node@v4 --node-version 20',  duration: '15s' },
        { step: 'Install',          command: 'pnpm install --frozen-lockfile',            duration: '45s' },
        { step: 'Lint',             command: 'pnpm lint',                                 duration: '20s' },
        { step: 'Test',             command: 'pnpm test',                                 duration: '90s' },
        { step: 'Build',            command: 'pnpm build',                                duration: '120s'},
        { step: 'Docker Build',     command: 'docker build -t $IMAGE_TAG .',              duration: '60s' },
        { step: 'Push to Registry', command: 'docker push $IMAGE_TAG',                   duration: '30s' },
        { step: 'Deploy to K8s',    command: 'kubectl apply -f k8s/',                    duration: '20s' },
        { step: 'Health Check',     command: 'kubectl rollout status deployment/',        duration: '30s' },
      ],
      infrastructureTargets: ['AWS EKS', 'AWS RDS (PostgreSQL)', 'AWS ElastiCache (Redis)', 'AWS S3', 'CloudFront CDN'],
      status: 'generated',
    };
  }
}
