export const CEREBRO_GLOSSARY: Record<string, string> = {
  'Enterprise AI': 'The deployment of artificial intelligence systems within enterprise organizations to automate processes, enhance decision-making, and create competitive advantages at scale.',
  'AI Agent': 'An autonomous software system powered by a large language model that can perceive its environment, reason, plan, and take actions to achieve specific goals without continuous human intervention.',
  'RAG': 'Retrieval-Augmented Generation — a technique that enhances LLM responses by retrieving relevant information from a knowledge base before generating an answer, reducing hallucinations and enabling up-to-date responses.',
  'LLM': 'Large Language Model — a deep learning model trained on vast text datasets capable of understanding and generating human language, reasoning, and performing complex cognitive tasks.',
  'MCP': 'Model Context Protocol — an open standard by Anthropic that enables AI models to securely connect with external tools, databases, APIs, and data sources in a standardized way.',
  'MLOps': 'Machine Learning Operations — the set of practices combining ML, DevOps, and data engineering to deploy and maintain ML models in production reliably and efficiently.',
  'AI Governance': 'The framework of policies, processes, and controls that organizations implement to ensure AI systems are used ethically, safely, compliantly, and in alignment with business objectives.',
  'Knowledge Graph': 'A structured representation of information where entities (people, concepts, products) and their relationships are stored as interconnected nodes, enabling semantic search and reasoning.',
  'Vector Database': 'A database optimized for storing and querying high-dimensional vector embeddings, enabling similarity search for AI applications like semantic search and RAG pipelines.',
  'Fine-Tuning': 'The process of further training a pre-trained LLM on domain-specific data to adapt its behavior, style, or knowledge for a specific use case.',
  'Prompt Engineering': 'The practice of designing and optimizing input instructions (prompts) to elicit the most accurate, relevant, and useful responses from AI language models.',
  'AI CoE': 'AI Center of Excellence — a centralized team that drives AI strategy, standardizes tools and practices, builds internal capability, and governs AI deployment across an enterprise.',
  'AI Factory': 'An operational model for producing AI solutions at scale, combining standardized processes, reusable components, and automation to accelerate AI development and deployment.',
  'HivePulse': 'CerebroHive\'s Enterprise AI Operating System — a unified control plane for deploying, managing, and orchestrating AI agents, workflows, and knowledge systems across the enterprise.',
  'Cerebro X': 'CerebroHive\'s Enterprise AI Intelligence Platform — the intelligence layer powering search, reasoning, knowledge graph management, and contextual AI across the platform.',
  'AIOps': 'AI for IT Operations — the use of AI and ML to automate and enhance IT operations including monitoring, event correlation, root cause analysis, and incident response.',
  'Autonomous Transformation': 'The enterprise-wide shift from human-operated processes to AI-operated workflows through intelligent agents, automated reasoning, and continuous self-improvement loops.',
  'Data Engineering': 'The discipline of designing and building systems that collect, store, transform, and serve data reliably for analytics and AI model training and inference.',
  'Hyperautomation': 'The use of AI, RPA, ML, and process mining together to identify and automate as many business processes as possible, creating end-to-end intelligent automation.',
  'Responsible AI': 'The practice of designing, developing, and deploying AI systems that are fair, explainable, robust, secure, and aligned with human values and regulatory requirements.',
};
