"use client";

import React from 'react';
import { EngineConfig } from '@/lib/data/industries/types';
import { SectionHeading } from '@/components/ui/SectionHeading';
import { motion } from 'framer-motion';
import { Layers, ArrowDown } from 'lucide-react';

export function IndustryERPIntegration({ erp, config }: { erp: string[], config: EngineConfig }) {
  if (!erp || erp.length === 0) return null;

  return (
    <section className="section-pad border-t border-border bg-background relative z-10">
      <div className="container-wide">
        <SectionHeading label="Ecosystem Integration" title="Quantiva ERP Mapping" description="Seamlessly integrate domain-specific AI with your core enterprise resource planning." />
        
        <div className="mt-16 flex flex-col md:flex-row gap-12 items-center">
          {/* Visual ERP mapping */}
          <div className="w-full md:w-1/2 flex flex-col items-center">
            {erp.map((module, idx) => (
              <React.Fragment key={idx}>
                <motion.div
                  initial={{ opacity: 0.4, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1 }}
                  className="w-full max-w-sm p-4 rounded-xl border border-border bg-surface-elevated flex items-center justify-between group cursor-default"
                >
                  <span className="font-bold text-text-primary">{module}</span>
                  <div className="w-8 h-8 rounded-full bg-surface flex items-center justify-center border border-border group-hover:border-primary-accent transition-colors">
                    <Layers size={14} style={{ color: config.primaryColor }} />
                  </div>
                </motion.div>
                
                {idx < erp.length - 1 && (
                  <motion.div
                    initial={{ opacity: 0.4 }}
                    whileInView={{ opacity: 1 }}
                    transition={{ delay: idx * 0.1 + 0.1 }}
                    className="h-6 flex items-center justify-center"
                  >
                    <ArrowDown size={16} className="text-border" />
                  </motion.div>
                )}
              </React.Fragment>
            ))}
          </div>

          <div className="w-full md:w-1/2">
            <h3 className="text-3xl font-space font-bold text-text-primary mb-6">Unified Enterprise Data</h3>
            <p className="text-lg text-text-secondary leading-relaxed mb-8">
              The Quantiva Integration Framework ensures that insights generated by domain-specific AI agents flow directly into your core business systems. 
            </p>
            <div className="p-6 rounded-2xl bg-surface border border-border border-l-4" style={{ borderLeftColor: config.secondaryColor }}>
              <p className="text-sm text-text-primary italic">
                "CerebroHive doesn't just analyze data in a silo—it acts on it through direct, secure integration with Quantiva ERP."
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
