import { IconMetadata } from './types';

export const iconRegistry: Record<string, IconMetadata> = {
  'CerebroXCore': { id: 'cerebroxcore', displayName: 'Cerebro X Core', category: 'branding', subcategory: '', keywords: ['cerebroxcore', 'gateway', 'ai'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'NeuralFabric': { id: 'neuralfabric', displayName: 'Neural Fabric', category: 'branding', subcategory: '', keywords: ['neuralfabric', 'network', 'ai'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'LivingDigitalTwin': { id: 'livingdigitaltwin', displayName: 'Living Digital Twin', category: 'branding', subcategory: '', keywords: ['livingdigitaltwin', 'twin', 'simulation'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'KnowledgeGalaxy': { id: 'knowledgegalaxy', displayName: 'Knowledge Galaxy', category: 'branding', subcategory: '', keywords: ['knowledgegalaxy', 'knowledge', 'graph'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'SemanticMemory': { id: 'semanticmemory', displayName: 'Semantic Memory', category: 'branding', subcategory: '', keywords: ['semanticmemory', 'memory', 'semantic'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'ReasoningEngine': { id: 'reasoningengine', displayName: 'Reasoning Engine', category: 'branding', subcategory: '', keywords: ['reasoningengine', 'reasoning', 'planner'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'EnterpriseBrain': { id: 'enterprisebrain', displayName: 'Enterprise Brain', category: 'branding', subcategory: '', keywords: ['enterprisebrain', 'brain', 'enterprise'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'AiOperatingSystem': { id: 'aioperatingsystem', displayName: 'AI Operating System', category: 'branding', subcategory: '', keywords: ['aioperatingsystem', 'os', 'ai'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'AgentSwarm': { id: 'agentswarm', displayName: 'Agent Swarm', category: 'branding', subcategory: '', keywords: ['agentswarm', 'agents', 'mesh'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'CognitivePipeline': { id: 'cognitivepipeline', displayName: 'Cognitive Pipeline', category: 'branding', subcategory: '', keywords: ['cognitivepipeline', 'pipeline', 'cognitive'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'HiveShield': { id: 'hiveshield', displayName: 'Hive Shield', category: 'branding', subcategory: '', keywords: ['hiveshield', 'guard', 'security'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'CerebroArchive': { id: 'cerebroarchive', displayName: 'Cerebro Archive', category: 'branding', subcategory: '', keywords: ['cerebroarchive', 'archive', 'storage'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'CerebroStudio': { id: 'cerebrostudio', displayName: 'Cerebro Studio', category: 'branding', subcategory: '', keywords: ['cerebrostudio', 'studio', 'builder'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'CerebroFlow': { id: 'cerebroflow', displayName: 'Cerebro Flow', category: 'branding', subcategory: '', keywords: ['cerebroflow', 'flow', 'workflow'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'CerebroInsight': { id: 'cerebroinsight', displayName: 'Cerebro Insight', category: 'branding', subcategory: '', keywords: ['cerebroinsight', 'insight', 'analytics'], tags: ['branding'], aliases: [], version: '1.0.0', introduced: '1.0.0', stability: 'stable' },
  'Database': {
    id: 'database',
    displayName: 'Database',
    category: 'database',
    subcategory: '',
    keywords: ["sql","storage","postgres","mysql"],
    tags: ["backend","storage"],
    aliases: ["db"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Server': {
    id: 'server',
    displayName: 'Server',
    category: 'infrastructure',
    subcategory: '',
    keywords: ["compute","node","bare-metal"],
    tags: ["backend","compute"],
    aliases: ["host"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Cloud': {
    id: 'cloud',
    displayName: 'Cloud',
    category: 'cloud',
    subcategory: '',
    keywords: ["aws","azure","gcp","hosting"],
    tags: ["cloud"],
    aliases: [],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'CloudCompute': {
    id: 'cloud-compute',
    displayName: 'CloudCompute',
    category: 'cloud',
    subcategory: '',
    keywords: ["processing","cloud-function"],
    tags: ["cloud","compute"],
    aliases: [],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Shield': {
    id: 'shield',
    displayName: 'Shield',
    category: 'security',
    subcategory: '',
    keywords: ["protection","firewall","secure"],
    tags: ["security"],
    aliases: [],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Lock': {
    id: 'lock',
    displayName: 'Lock',
    category: 'security',
    subcategory: '',
    keywords: ["secure","encryption","private"],
    tags: ["security"],
    aliases: [],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Workflow': {
    id: 'workflow',
    displayName: 'Workflow',
    category: 'workflow',
    subcategory: '',
    keywords: ["pipeline","process","flow"],
    tags: ["automation"],
    aliases: [],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Settings': {
    id: 'settings',
    displayName: 'Settings',
    category: 'navigation',
    subcategory: '',
    keywords: ["preferences","options","config"],
    tags: ["ui"],
    aliases: ["gear"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Search': {
    id: 'search',
    displayName: 'Search',
    category: 'navigation',
    subcategory: '',
    keywords: ["find","lookup","query"],
    tags: ["ui"],
    aliases: ["magnifier"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'AiBrain': {
    id: 'ai-brain',
    displayName: 'AiBrain',
    category: 'ai',
    subcategory: '',
    keywords: ["intelligence","neural","smart"],
    tags: ["ai"],
    aliases: ["brain"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Robot': {
    id: 'robot',
    displayName: 'Robot',
    category: 'agents',
    subcategory: '',
    keywords: ["agent","automaton","bot"],
    tags: ["ai","agent"],
    aliases: ["bot"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'FileCode': {
    id: 'file-code',
    displayName: 'FileCode',
    category: 'files',
    subcategory: '',
    keywords: ["source","script","json"],
    tags: ["developer"],
    aliases: ["code"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'FileJson': {
    id: 'file-json',
    displayName: 'FileJson',
    category: 'files',
    subcategory: '',
    keywords: ["data","api"],
    tags: ["developer"],
    aliases: ["json"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'ChartBar': {
    id: 'chart-bar',
    displayName: 'ChartBar',
    category: 'analytics',
    subcategory: '',
    keywords: ["graph","data","metrics"],
    tags: ["data"],
    aliases: ["graph"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'ChartPie': {
    id: 'chart-pie',
    displayName: 'ChartPie',
    category: 'analytics',
    subcategory: '',
    keywords: ["graph","data","metrics"],
    tags: ["data"],
    aliases: ["pie"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Home': {
    id: 'home',
    displayName: 'Home',
    category: 'dashboard',
    subcategory: '',
    keywords: ["main","start","landing"],
    tags: ["ui"],
    aliases: ["house"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'User': {
    id: 'user',
    displayName: 'User',
    category: 'navigation',
    subcategory: '',
    keywords: ["person","account","profile"],
    tags: ["ui"],
    aliases: ["person"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Users': {
    id: 'users',
    displayName: 'Users',
    category: 'enterprise',
    subcategory: '',
    keywords: ["team","group","organization"],
    tags: ["ui"],
    aliases: ["team"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Building': {
    id: 'building',
    displayName: 'Building',
    category: 'enterprise',
    subcategory: '',
    keywords: ["company","office","hq"],
    tags: ["business"],
    aliases: ["company"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'CheckCircle': {
    id: 'check-circle',
    displayName: 'CheckCircle',
    category: 'status',
    subcategory: '',
    keywords: ["success","done","complete"],
    tags: ["status"],
    aliases: ["success"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'AlertCircle': {
    id: 'alert-circle',
    displayName: 'AlertCircle',
    category: 'status',
    subcategory: '',
    keywords: ["warning","error","danger"],
    tags: ["status"],
    aliases: ["warning"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Loader': {
    id: 'loader',
    displayName: 'Loader',
    category: 'status',
    subcategory: '',
    keywords: ["spinner","loading","wait"],
    tags: ["status"],
    aliases: ["loading"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Terminal': {
    id: 'terminal',
    displayName: 'Terminal',
    category: 'developer',
    subcategory: '',
    keywords: ["cli","console","prompt"],
    tags: ["developer"],
    aliases: ["console"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  },
  'Api': {
    id: 'api',
    displayName: 'Api',
    category: 'developer',
    subcategory: '',
    keywords: ["endpoint","integration","rest"],
    tags: ["developer"],
    aliases: ["webhook"],
    version: '1.0.0',
    introduced: '2026.07',
    stability: 'stable',
    deprecated: false,
    animated: false,
    duotone: true
  }
};
