import { IconCategory, IconMetadata } from './types';

export const iconRegistry: Record<string, IconMetadata> = {
  'AiStrategy': { name: 'AiStrategy', category: 'navigation', keywords: [] },
  'AiAgents': { name: 'AiAgents', category: 'navigation', keywords: [] },
  'EnterprisePlatforms': { name: 'EnterprisePlatforms', category: 'navigation', keywords: [] },
  'Cloud': { name: 'Cloud', category: 'navigation', keywords: [] },
  'DataEngineering': { name: 'DataEngineering', category: 'navigation', keywords: [] },
  'Settings': { name: 'Settings', category: 'navigation', keywords: [] },
  'Help': { name: 'Help', category: 'navigation', keywords: [] },
  'Logout': { name: 'Logout', category: 'navigation', keywords: [] },
  'AgentOrchestrator': { name: 'AgentOrchestrator', category: 'architecture', keywords: [] },
  'KnowledgeGraph': { name: 'KnowledgeGraph', category: 'architecture', keywords: [] },
  'LlmService': { name: 'LlmService', category: 'architecture', keywords: [] },
  'VectorDb': { name: 'VectorDb', category: 'architecture', keywords: [] },
  'Send': { name: 'Send', category: 'chat', keywords: [] },
  'Thinking': { name: 'Thinking', category: 'chat', keywords: [] },
  'AiResponse': { name: 'AiResponse', category: 'chat', keywords: [] },
  'UserMessage': { name: 'UserMessage', category: 'chat', keywords: [] },
  'Success': { name: 'Success', category: 'status', keywords: [] },
  'Info': { name: 'Info', category: 'status', keywords: [] },
  'Warning': { name: 'Warning', category: 'status', keywords: [] },
  'Loading': { name: 'Loading', category: 'status', keywords: [] },
  'Pdf': { name: 'Pdf', category: 'files', keywords: [] },
  'Document': { name: 'Document', category: 'files', keywords: [] },
  'CodeFile': { name: 'CodeFile', category: 'files', keywords: [] },
  'AiRoadmap': { name: 'AiRoadmap', category: 'actions', keywords: [] },
  'ModernizeErp': { name: 'ModernizeErp', category: 'actions', keywords: [] },
  'BuildAiAgent': { name: 'BuildAiAgent', category: 'actions', keywords: [] },
  'GenerateProposal': { name: 'GenerateProposal', category: 'actions', keywords: [] },
  'RoiEstimate': { name: 'RoiEstimate', category: 'actions', keywords: [] },
  'MoreOptions': { name: 'MoreOptions', category: 'actions', keywords: [] },
  'ThumbsUp': { name: 'ThumbsUp', category: 'feedback', keywords: [] },
  'ThumbsDown': { name: 'ThumbsDown', category: 'feedback', keywords: [] },
  'Share': { name: 'Share', category: 'feedback', keywords: [] },
  'Bookmark': { name: 'Bookmark', category: 'feedback', keywords: [] },
  'Star': { name: 'Star', category: 'feedback', keywords: [] },
  'More': { name: 'More', category: 'feedback', keywords: [] },
  'ClearChat': { name: 'ClearChat', category: 'chat', keywords: [] },
  'NewChat': { name: 'NewChat', category: 'chat', keywords: [] },
};
