import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@cerebro/db';
import { FORGE_DOCS_SCHEMA } from '@cerebro/ai';
import { projectGraph } from '@cerebro/workflow';
import { AgentOrchestratorService } from '../agent/agent-orchestrator.service';

export interface DocSection {
  title: string;
  type: 'api_reference' | 'architecture' | 'onboarding' | 'user_manual' | 'runbook' | 'changelog';
  wordCount: number;
  status: 'generated' | 'pending';
  filePath: string;
}

export interface DocsResult {
  sections: DocSection[];
  totalWords: number;
  totalPages: number;
  status: 'generated';
}

/** Shape returned by the AI for structured doc planning */
interface AIDocsResult {
  sections: Array<{
    title: string;
    type: 'api_reference' | 'architecture' | 'onboarding' | 'user_manual' | 'runbook' | 'changelog';
    summary: string;
    wordCount: number;
    filePath: string;
  }>;
}

@Injectable()
export class DocsService {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly orchestrator: AgentOrchestratorService,
  ) {}

  async generate(projectId: string): Promise<DocsResult> {
    const ctx = projectGraph.getOrThrow(projectId);

    const modules   = ctx.plan?.modules.map(m => m.name).join(', ') ?? 'core';
    const stack     = ctx.plan?.stack ? JSON.stringify(ctx.plan.stack) : 'Node.js / PostgreSQL';
    const services  = ctx.architecture?.services.map(s => `${s.name}:${s.port}`).join(', ') ?? '';
    const adrs      = ctx.architecture?.decisions.map(d => d.title).join('; ') ?? '';
    const actors    = ctx.plan?.actors.join(', ') ?? 'Admin, User';

    const userPrompt = `Plan and write documentation for this project.

Project: ${ctx.prompt}
Modules: ${modules}
Actors/Roles: ${actors}
Tech stack: ${stack}
${services ? `Services: ${services}` : ''}
${adrs ? `Architecture decisions: ${adrs}` : ''}

Generate a 6-section documentation plan. For each section estimate realistic wordCount based on project complexity:
1. API Reference (api_reference) — filePath: docs/api-reference.md — every endpoint, request/response schemas, error codes, auth headers, examples
2. Architecture Guide (architecture) — filePath: docs/architecture.md — system overview, service map, data flows, ADRs, sequence diagrams
3. Developer Onboarding (onboarding) — filePath: docs/getting-started.md — prerequisites, local setup, env vars, branching, PR checklist, conventions
4. User Manual (user_manual) — filePath: docs/user-manual.md — role-based guides for: ${actors}
5. Deployment Runbook (runbook) — filePath: docs/runbook.md — deployment steps, env config, rollback, monitoring, alerting responses, incident procedures
6. Changelog (changelog) — filePath: CHANGELOG.md — v1.0.0 initial release with all features, breaking changes section, migration guide

wordCount per section must be proportional to complexity. A full API Reference for ${ctx.plan?.totalApis ?? 20}+ endpoints warrants 3000–6000 words. A runbook for ${services ? services.split(',').length : 3} services warrants 2000–3500 words.`;

    projectGraph.advancePhase(projectId, 'monitoring');

    const result = await this.orchestrator.runAgent<AIDocsResult>({
      projectId,
      agentType: 'docs',
      phase: 'monitoring',
      userPrompt,
      schema: FORGE_DOCS_SCHEMA,
      schemaDescription: 'AIDocsResult — 6-section documentation plan with AI-estimated word counts',
    });

    const aiSections = result.output.sections;

    // Persist doc artifacts to DB
    const p = this.prisma;
    await p.$transaction([
      p.project.update({
        where: { id: projectId },
        data: { forgePhase: 'monitoring', forgeStatus: 'completed' },
      }),
      ...aiSections.map(s =>
        p.generatedArtifact.upsert({
          where: { projectId_filePath: { projectId, filePath: s.filePath } },
          create: {
            projectId,
            filePath: s.filePath,
            type: 'file',
            language: 'markdown',
            content: `# ${s.title}\n\n> Generated by CerebroForge™ Documentation Agent\n\n${s.summary}`,
            lineCount: Math.round(s.wordCount / 8),
            agentType: 'docs',
            status: 'done',
          },
          update: {
            content: `# ${s.title}\n\n> Generated by CerebroForge™ Documentation Agent\n\n${s.summary}`,
            lineCount: Math.round(s.wordCount / 8),
            status: 'done',
          },
        }),
      ),
    ]);

    const sections: DocSection[] = aiSections.map(s => ({
      title:     s.title,
      type:      s.type,
      wordCount: s.wordCount,
      status:    'generated' as const,
      filePath:  s.filePath,
    }));

    const totalWords = sections.reduce((sum, s) => sum + s.wordCount, 0);

    return {
      sections,
      totalWords,
      totalPages: Math.round(totalWords / 250),  // ~250 words per A4 page
      status: 'generated',
    };
  }
}
