"use client";

import React from "react";
import { BookOpen, ArrowDown, Bot, Database, Target, ArrowRight } from "lucide-react";

const research = [
  {
    title: "Enterprise Agent Memory",
    paper: "Scaling Long-Term Context in Multi-Agent Swarms",
    desc: "Our breakthrough in persistent agent memory allows systems to remember conversational context, corporate policies, and past decisions across sessions.",
    product: "AgentOS",
    productIcon: Bot,
    color: "text-[#7B61FF]"
  },
  {
    title: "Reasoning Systems",
    paper: "Deterministic Routing in Non-Deterministic LLMs",
    desc: "A novel architecture that forces probabilistic language models to generate deterministic JSON outputs, guaranteeing compliance for ERP integration.",
    product: "Quantiva ERP",
    productIcon: Target,
    color: "text-accent-primary"
  }
];

export default function ResearchHighlights() {
  return (
    <section className="py-24 border-b border-border bg-background">
      <div className="container-wide">
        
        <div className="flex flex-col md:flex-row justify-between items-end mb-16 gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface border border-border text-[10px] uppercase tracking-widest text-warning font-bold mb-6">
              <BookOpen size={12} /> CerebroHive Research
            </div>
            <h2 className="text-3xl md:text-5xl font-space font-bold text-text-primary mb-4">From Lab to Production.</h2>
            <p className="text-lg text-text-secondary max-w-2xl font-inter">
              We don't just publish papers. Every breakthrough generated by our research institute is immediately integrated into our platform.
            </p>
          </div>
          <button className="px-6 py-3 border border-border rounded-lg text-sm font-bold uppercase tracking-widest text-text-primary hover:bg-surface transition-colors whitespace-nowrap">
            Visit Research Institute
          </button>
        </div>

        <div className="grid md:grid-cols-2 gap-12">
          {research.map((item, i) => (
            <div key={i} className="flex flex-col relative group">
              
              {/* The Research */}
              <div className="bg-surface border border-border rounded-2xl p-8 relative z-10 hover:border-border-strong transition-colors">
                <div className="text-[10px] uppercase tracking-widest text-text-muted font-bold mb-3 flex items-center gap-2">
                  <BookOpen size={12} /> Research Area
                </div>
                <h3 className="text-2xl font-space font-bold text-text-primary mb-2">{item.title}</h3>
                <div className="text-xs font-bold text-warning mb-4">Paper: {item.paper}</div>
                <p className="text-sm text-text-secondary leading-relaxed">{item.desc}</p>
                <div className="mt-6 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-text-primary group-hover:text-[#FFB300] transition-colors cursor-pointer">
                  Read Abstract <ArrowRight size={14} />
                </div>
              </div>

              {/* The Connection */}
              <div className="flex justify-center -my-3 relative z-20">
                <div className="w-8 h-8 rounded-full bg-background border border-border flex items-center justify-center">
                  <ArrowDown size={14} className="text-text-muted group-hover:text-text-primary transition-colors" />
                </div>
              </div>

              {/* The Product */}
              <div className="bg-black/40 border border-border rounded-2xl p-8 relative z-10">
                <div className="text-[10px] uppercase tracking-widest text-text-muted font-bold mb-4">Integrated Into Platform</div>
                <div className="flex items-center gap-4">
                  <div className={`w-12 h-12 rounded-xl bg-surface-elevated flex items-center justify-center ${item.color}`}>
                    <item.productIcon size={24} />
                  </div>
                  <h4 className="text-xl font-space font-bold text-text-primary">{item.product}</h4>
                </div>
              </div>

            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
