export type DomainVocabulary = { entities: string[]; business: string[]; metrics: Array<[string,string]>; relationships: Array<[string,string,string]> };
const packs: Record<string, DomainVocabulary> = {
  airport:{entities:['airport','terminal','gate','runway','aircraft','passenger','baggage','flight','ground-vehicle','weather'],business:['staff'],metrics:[['passenger-flow','people/hour'],['delay','minute'],['runway-utilization','percent']],relationships:[['airport','contains','terminal'],['terminal','contains','gate'],['flight','uses','runway'],['passenger','travels-on','flight']]},
  'commercial-bank':{entities:['bank','branch'],business:['customer','account','loan','transaction','employee','risk-control'],metrics:[['transaction-volume','count/hour'],['liquidity','currency'],['default-risk','percent']],relationships:[['bank','operates','branch'],['customer','owns','account'],['account','records','transaction'],['customer','holds','loan']]},
  hospital:{entities:['hospital','ward','bed','medical-device'],business:['patient','clinician','appointment'],metrics:[['occupancy','percent'],['wait-time','minute'],['device-health','percent']],relationships:[['hospital','contains','ward'],['ward','contains','bed'],['patient','assigned-to','bed'],['clinician','cares-for','patient']]},
  'supply-chain':{entities:['network','warehouse','distribution-hub','truck','shipment'],business:['supplier','order','customer'],metrics:[['inventory','count'],['lead-time','hour'],['on-time-delivery','percent']],relationships:[['network','contains','warehouse'],['warehouse','dispatches','shipment'],['truck','carries','shipment'],['order','fulfilled-by','shipment']]},
  'smart-building':{entities:['building','floor','zone','hvac-unit','meter'],business:['occupant'],metrics:[['energy-use','kWh'],['temperature','celsius'],['occupancy','count']],relationships:[['building','contains','floor'],['floor','contains','zone'],['hvac-unit','serves','zone']]},
  'energy-grid':{entities:['grid','substation','transformer','feeder','meter'],business:['customer'],metrics:[['load','MW'],['frequency','Hz'],['voltage','V']],relationships:[['grid','contains','substation'],['substation','feeds','feeder'],['transformer','serves','meter']]},
  'data-center':{entities:['data-center','hall','rack','server','cooling-unit','ups'],business:['workload'],metrics:[['power','kW'],['temperature','celsius'],['utilization','percent']],relationships:[['data-center','contains','hall'],['hall','contains','rack'],['rack','contains','server'],['server','runs','workload']]},
  factory:{entities:['factory','production-line','machine','motor','sensor'],business:['worker','inventory','order'],metrics:[['temperature','celsius'],['vibration','mm/s'],['production-rate','percent']],relationships:[['factory','contains','production-line'],['production-line','contains','machine'],['machine','contains','motor']]},
};
export function vocabularyFor(domain:string,description:string):DomainVocabulary { const key=domain.toLowerCase().trim().replace(/\s+/g,'-'); if(packs[key]) return packs[key]; const nouns=[...new Set(description.toLowerCase().match(/[a-z][a-z-]{3,}/g) ?? [])].filter(word=>!['with','that','from','this','their','into','system'].includes(word)).slice(0,8); const entities=nouns.length>=2?nouns:['system','component']; return {entities,business:[],metrics:[['health','percent'],['throughput','count/hour']],relationships:entities.slice(1).map(entity=>[entities[0],'contains',entity])}; }
