"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
type Tab = "reports" | "anomalies" | "forecast";
const REPORTS = [
  { name: "Weekly Executive Digest", cadence: "Every Monday 7:00 AM", recipients: 8, lastRun: "2026-07-21", status: "delivered" },
  { name: "Monthly Board Pack", cadence: "1st of month 6:00 AM", recipients: 12, lastRun: "2026-07-01", status: "delivered" },
  { name: "Real-time Revenue Dashboard", cadence: "Live", recipients: 24, lastRun: "Now", status: "live" },
  { name: "Agent Performance Report", cadence: "Daily 8:00 AM", recipients: 5, lastRun: "2026-07-25", status: "delivered" },
];
const ANOMALIES = [
  { metric: "API error rate", delta: "+340%", detected: "2026-07-24 22:15", severity: "critical", resolved: true },
  { metric: "Token spend / run", delta: "+28%", detected: "2026-07-25 04:00", severity: "warning", resolved: false },
  { metric: "New customer signups", delta: "-45%", detected: "2026-07-23 09:00", severity: "warning", resolved: false },
];
export default function CerebroInsightPage() {
  const [tab, setTab] = useState<Tab>("reports");
  return (
    <main className="mx-auto max-w-6xl px-6 pb-24 pt-8">
      <Link href="/platform" className="inline-flex items-center gap-1.5 text-xs font-semibold uppercase tracking-widest text-text-secondary hover:text-primary-accent transition-colors"><ArrowLeft size={14} /> Platform</Link>
      <p className="mt-5 text-xs font-semibold uppercase tracking-[0.3em] text-primary-accent">CerebroInsight™ · Tier 4</p>
      <h1 className="mt-2 text-3xl font-bold text-text-primary md:text-4xl">Business Intelligence — automated reports, anomaly detection, AI forecasting</h1>
      <p className="mt-3 max-w-2xl text-text-secondary">CerebroInsight generates business reports automatically, detects metric anomalies in real time, and runs AI-powered forecasts against any business metric. Every report is generated by an agent pipeline with cited data sources.</p>
      <div className="mt-6 flex flex-wrap gap-2 border-b border-border">
        {(["reports","anomalies","forecast"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 text-sm font-semibold capitalize transition-colors ${tab===t?"border-b-2 border-primary-accent text-primary-accent":"text-text-secondary hover:text-text-primary"}`}>{t}</button>)}
      </div>
      {tab==="reports" && (
        <div className="mt-6 space-y-2">
          {REPORTS.map(r=>(
            <div key={r.name} className="rounded-xl border border-border bg-surface/40 p-4">
              <div className="flex items-center justify-between gap-2">
                <div><p className="font-semibold text-text-primary">{r.name}</p><p className="mt-0.5 text-xs text-text-secondary">{r.cadence} · {r.recipients} recipients</p></div>
                <div className="flex items-center gap-2"><p className="text-xs text-text-secondary">Last: {r.lastRun}</p><span className={`rounded-full border px-2 py-0.5 text-xs font-semibold ${r.status==="live"?"border-primary-accent/40 text-primary-accent bg-primary-accent/10":"border-border text-text-secondary"}`}>{r.status}</span></div>
              </div>
            </div>
          ))}
        </div>
      )}
      {tab==="anomalies" && (
        <div className="mt-6 space-y-3">
          <p className="text-xs text-text-secondary">Anomaly detection uses Prophet + Z-score on rolling 30-day baselines. Alerts fire when a metric deviates beyond 3σ or exceeds a defined threshold change within a 1-hour window.</p>
          {ANOMALIES.map(a=>(
            <div key={a.metric} className={`rounded-xl border p-4 ${a.severity==="critical"?"border-red-500/40 bg-red-500/5":"border-yellow-400/40 bg-yellow-400/5"}`}>
              <div className="flex items-center justify-between gap-2">
                <div><p className="font-semibold text-text-primary">{a.metric}</p><p className="mt-0.5 text-xs text-text-secondary">{a.detected}</p></div>
                <div className="flex items-center gap-2"><span className={`text-lg font-bold ${a.delta.startsWith("+")?"text-red-400":"text-yellow-400"}`}>{a.delta}</span>{a.resolved&&<span className="text-xs text-primary-accent">resolved</span>}</div>
              </div>
            </div>
          ))}
        </div>
      )}
      {tab==="forecast" && (
        <div className="mt-6 space-y-4">
          <p className="text-xs text-text-secondary">Prophet + LSTM ensemble forecasting on any platform metric. Select a metric and horizon to generate a forecast with confidence intervals.</p>
          {[["MRR (90-day forecast)","$1.42M","±$120K","83%"],["Agent runs (30-day)","38,400","±2,800","91%"],["Token spend (30-day)","$184,000","±$22,000","87%"],["Customer count (90-day)","347","±28","79%"]].map(([metric,point,ci,conf])=>(
            <div key={String(metric)} className="rounded-xl border border-border bg-surface/40 p-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-text-secondary">{metric}</p>
              <p className="mt-2 text-2xl font-bold text-primary-accent">{point} <span className="text-sm font-normal text-text-secondary">{ci}</span></p>
              <p className="mt-0.5 text-xs text-text-secondary">Confidence: {conf}</p>
            </div>
          ))}
        </div>
      )}
    </main>
  );
}
