name: Semgrep Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * 0' # Weekly

permissions:
  contents: read
  security-events: write
  actions: read

defaults:
  run:
    working-directory: OPC/cerebro-hive-website

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v7
      - name: Semgrep
        run: semgrep scan --config auto
