name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *' # Daily

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 90
          days-before-close: 14
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          exempt-issue-labels: 'security,documentation,research,enhancement,good first issue'
          exempt-pr-labels: 'security,documentation,research,enhancement,good first issue'
